content/en/docs/setup/platforms/OLCNE/OLCNE.md

This pull request fixes invalid verrazzano spec references for installing with OLCNE.  This problem was reported in the verrazzano-interest channel.

VZ-3559: fix verrazzano spec references for OLCNE setup

---

content/en/docs/troubleshooting/diagnostictools/analysisadvice/IngressLBLimitExceeded.md

Added analysis advice for troubleshooting docs for the case when NGINX ingress installations fail if the load service limits are reached.
VZ-3270

Advice for when NGINX Ingress Controller installation fails due load balancer service limit

---

content/en/docs/troubleshooting/diagnostictools/analysisadvice/IngressLBLimitExceeded.md

PR to cherry-pick VZ-3270 doc work (analysis tool detection for load balancer service limit issue) to release-1.0. The PR was approved for merging with master.

Advice for when NGINX Ingress Controller installation fails due load balancer service limit (#281)

---

config/_default/markup.toml
content/en/docs/setup/platforms/OLCNE/OLCNE.md

Change the doc to tell the user to get the load balancer backend ports after installation.  Also, change the healthcheck port to 0 as mentioned at https://docs.oracle.com/en-us/iaas/Content/Balance/Tasks/managingbackendsets.htm#GetBackendSetHealth

VZ-3601 doc for OLCNE Load Balancers

---

content/en/docs/setup/platforms/OLCNE/OLCNE.md

Add instructions for configuration kube-apiserver on OLCNE for Verrazzano installations on Kubernetes 1.18 and 1.19.

VZ-3822 add instructions to configure kube-apiserver for OLCNE

---

content/en/docs/guides/lift-and-shift/lift-and-shift.md
content/en/docs/guides/lift-and-shift/mysql-oam.yaml
content/en/docs/guides/lift-and-shift/vz-application-modified.yaml

Backporting the updated Lift-Shift instructions for the ToDo List application into release 1.0. 
- Fixes for - VZ-3431, VZ-3830, VZ-3831.
- Removed ApplicationConfiguration and tls prefix from MySQL Yaml.
- Updated vz-application-modified.yaml to include MySQL Verrazzano components.
- Updated Lift and shift instructions to do the necessary changes.

Backport Lift-Shift instructions for ToDo List application

---

content/en/docs/setup/upgrade/_index.md

This section is meant to inform users on how to restart applications to meet requirements of a major upgrade in Istio. This situation will occur when upgrading to the 1.1 release.

VZ-3368 Document Istio Upgrade Details

---

config/_default/params.toml
content/en/docs/quickstart/_index.md
content/en/docs/releasenotes/_index.md
content/en/docs/setup/install/installation.md
content/en/docs/setup/uninstall/uninstall.md
content/en/docs/setup/versions.md

PR with updates for the 1.0.3 patch release and fixes to commands to include the verrazzano-install namespace.
**NOTE**: The patch release date in the versions.md file must be updated with the release date before this PR is merged.

Updates for release 1.0.3

---

content/en/docs/quickstart/_index.md
content/en/docs/releasenotes/_index.md
content/en/docs/setup/install/installation.md
content/en/docs/setup/uninstall/uninstall.md
content/en/docs/setup/versions.md

This is the port from the release-1.0 branch that includes updates for the 1.0.3 release as well as fixes to several commands that are missing `-n verrazzano-install`.
**Note** I did not update the release version references as those will get updated when version 1.1 is released.

Updates for release 1.0.3 (master)

---

content/en/docs/setup/upgrade/_index.md

Add a section for application restart during upgrade.  Remove the restart annotation doc, since we do not want that exposed to the end-user.  Also, do some minor reorg, cleanup.

 VZ-3985 - add application restart section

---

content/en/docs/releasenotes/_index.md
content/en/docs/setup/versions.md

Updated the Elasticsearch version to 7.10.2 including a new release notes 1.1 section.

VZ-3988: Build elasticsearch from source and clear of vulnerabilities.

---

content/en/docs/releasenotes/_index.md
content/en/docs/setup/install/multicluster.md
content/en/docs/setup/platforms/Generic/generic.md
content/en/docs/setup/platforms/kind/kind.md

After discussion with Style Guide experts, decided to use lowercase kind (tool name) and command, `kind`.

change kind capitalization

---

content/en/docs/setup/install/multicluster.md

Use snake case vs. camel case in shell variable in multi-cluster

---

content/en/docs/monitoring/oci-logging/oci-logging.md

Update the OCI Logging page to include information on how to override the OCI Log object on individual namespaces.

VZ-4149: Add information for overriding default OCI Log objects

---

content/en/docs/guides/lift-and-shift/lift-and-shift.md

As per bug Doc 33152590, "Maybe add commands for both Linux and Windows for each step **OR** mention that
this example assumes that the on-premises WebLogic Server domain is on Linux."

add example assumption

---

content/en/docs/faq/FAQ.md
content/en/docs/troubleshooting/known-issues.md

* Add FAQ to allow Chrome to prompt for untrusted certificates
* update and move FAQ
* hide known issues doc
Co-authored-by: Rosemary Marano <rosemary.marano@oracle.com>

Add FAQ to allow Chrome to prompt for untrusted certificates (#369)

---

content/en/docs/guides/app-deployment/application-deployment-guide.md

Back port doc to address Doc 33152524 - DOC UPDATE FOR “ACCESS THE APPLICATION’S METRICS” and Doc 33160226 - UPDATE DOCUMENTATION ON HOW TO CONFIGURE DASHBOARDS FOR PROMETHEUS, KIBANA AND GRAFANA

update app metrics and logs access info (#393)

---

content/en/docs/quickstart/_index.md

quick start guide instructions for hello-helidon was missing namespace on the apply, it was correct in the samples doc for hello-helidon, but it would not work correctly if a customer just used the instructions directly presented in the quick start guide.

VZ-4959 add namespace to quickstart instructions for hello-helidon

---

content/en/docs/samples/helidon-config/_index.md
content/en/docs/samples/hello-helidon/_index.md
content/en/docs/samples/multicluster/sock-shop/_index.md
content/en/docs/samples/multicluster/todo-list/_index.md
content/en/docs/samples/sock-shop.md
content/en/docs/samples/spring-boot.md
content/en/docs/samples/todo-list.md

Backport Fix to Remove References to Variety of URLs in Example Docs to the 1.1 docs

backport-fix-url

---

content/en/docs/setup/customizing/ociLoadBalancerIPs.md

Backport to 1.1:
* Update Customizing OKE LBs doc

VZ-5064.  Backport documentation for using private LBs with OKE to 1.1 docs

---

content/en/docs/setup/upgrade/_index.md

Remove the newlines from the restart the upgrade command in the 1.1 Upgrade docs.

remove newlines from command

---

content/en/docs/quickstart/_index.md

Change the quick start VZ CR to use persistence.  This is a temporary way to prevent issues related to upgrade of Verrazzano installations without persistence.  This can be back ported to the 1.1 and 1.2 code lines.

VZ-5031: Update dev profile to use persistent storage by default

---

content/en/docs/troubleshooting/troubleshooting-multicluster.md

Updated the multicluster troubleshooting section to re-register the managed cluster in case of the DNS changes on the admin cluster leading to managed cluster status unavailable in the Rancher console.

VZ-6184 Update to Multicluster Troubleshooting documentation

---

config/_default/params.toml
content/en/docs/releasenotes/_index.md
content/en/docs/setup/prereqs.md

Backport the RNs for v1.3.1 and update params.toml accordingly.

Release 1.3.1 RN backport

---

content/en/docs/setup/prereqs.md

Update the "Installed Components" table to reference new Rancher 2.6.5 version.

VZ-6390: Bump Rancher version

---

content/en/docs/setup/platforms/OLCNE/OLCNE.md

This PR includes to improvements.  First, the order of the install guide and OCI setup instructions is reversed, making easier to see the installation instructions.  Second, a kubectl snippet is included to show a possible oci-ccm configuration that will work for verrazzano.

Reverse OLCNE install guide sections

---

content/en/docs/setup/platforms/OLCNE/OLCNE.md

This OCNE issue was reported by a customer but I have also run into this. The external IP validating webhook needs to be disabled or configured to allow load balancer IP addresses, otherwise the Verrazzano installation fails.
This PR adds a note to the OCNE setup instructions.

VZ-6383: Add note about disabling external IP validation

---

content/en/docs/setup/cli/_index.md
content/en/docs/troubleshooting/diagnostictools/VZBugReportCLI.md
content/en/docs/troubleshooting/diagnostictools/VerrazzanoAnalysisTool.md
content/en/docs/troubleshooting/diagnostictools/analysisadvice/_index.md

Summary of changes:
* Updated existing Analysis tool documentation to reflect the usage of new command "vz analyze" by removing old way of getting the cluster-dump (cluster-snapshot)
* Added a new document for "VZ bug-report" command referring https://confluence.oraclecorp.com/confluence/pages/viewpage.action?spaceKey=VZ&title=Verrazzano+Bug+Report+CLI
* Updated the CLI index to reflect the new command "bug-report" from available commands

Documentation for vz analyze and vz bug-report commands

---

content/en/docs/access/_index.md

Rancher from 1.4 support both [login with Keycloak and local user](https://github.com/verrazzano/verrazzano/pull/3768) . This PR for corresponding docs changes.

VZ-5010: Docs regarding Keycloak login for Rancher

---

content/en/docs/setup/install/installation.md
content/en/docs/setup/upgrade/_index.md

The Verrazzano Lite distribution includes verrazzano-platform-operator.yaml, which was operator.yaml in the earlier releases. This change updates operator YAML file in the documentation.

Documentation change for the renaming of operator.yaml in the distribution

---

content/en/docs/monitoring/tracing/jaeger-tracing.md

Enabled jaegerOperator in some YAML where it was missing and fixed indentation on an example VZ CR.

Enable jaegerOperator in yaml and fix indentation

---

config/_default/params.toml
content/en/docs/setup/private-registry/private-registry-full-distribution.md

This change updates the location from where the Verrazzano release bundles can be downloaded, in the documentation for setting up Private Registry.

Update download location of verrazzano release bundles for private registry setup

---

config/_default/params.toml
content/en/docs/setup/private-registry/private-registry-full-distribution.md

This change updates the version of Verrazzano displayed in Oracle Software Delivery Cloud, in private registry setup for release-1.4

Fix version of Verrazzano displayed in Oracle Software Delivery Cloud, in private registry setup

---

config/_default/params.toml
content/en/docs/setup/private-registry/private-registry-full-distribution.md

This change updates the version of Verrazzano displayed in Oracle Software Delivery Cloud, in private registry setup.

Fix version of Verrazzano displayed in Oracle Software Delivery Cloud, in private registry setup 

---

content/en/docs/customize/dns.md
content/en/docs/networking/traffic/net-traffic.md

host name (n) - Use two words, but use hostname as a one-word variable in code instructions and commands.

fix spelling

---

content/en/docs/customize/ociLoadBalancerIPs.md

VZ-7390 The documented sample provided for customizing OCI Load Balancers [LINK](https://verrazzano.io/latest/docs/customize/ociloadbalancerips/) contains a wrong annotation value.
`service.beta.kubernetes.io/oci-load-balancer-internal: true`. Since `true` is treated as a boolean value, the webhook validation fails and the VZ CR creation fails. This PR is for fixing the documentation with the sample VZ CR having `true` values enclosed in quotes.

VZ-7390 Documentation fix for enclosing true in quotes for OCI LB annotation

---

content/en/docs/setup/prereqs.md

In WKO 4.0, the User Guide has been replaced by other sections, hence the broken link to it.

fix broken link

---

content/en/docs/samples/todo-list.md

This PR revises the instructions to monitor the deployed ToDo List application after the .yaml files are applied. The previous instructions have a `kubectl wait` command that errored due to the `tododomain-adminserver` pod not existing. This PR aims to improve this `kubectl wait` command and make any possible errors clear to users.

VZ-4505: ToDo List Instructions Don't Wait for Pod to Exist

---

content/en/docs/quickstart/_index.md

Previous path (using `ghlink`) resulted in resources that were not deleted, for example:
$ kubectl apply -f https://raw.githubusercontent.com/verrazzano/verrazzano/master/examples/hello-helidon/hello-helidon-comp.yaml -n hello-helidon
**component**.core.oam.dev/hello-helidon-component created
$kubectl delete -f https://raw.githubusercontent.com/verrazzano/verrazzano/master/examples/hello-helidon/hello-helidon-comp.yaml
Error from server (NotFound): error when deleting "https://raw.githubusercontent.com/verrazzano/verrazzano/master/examples/hello-helidon/hello-helidon-comp.yaml": **components**.core.oam.dev "hello-helidon-component" not found
Whereas, in the Hello Helidon example apps, the current path (using `release_source_url` instead) worked correctly:
$ kubectl apply -f …

edit path to example files

---

content/en/docs/monitoring/metrics/metrics.md
content/en/docs/quickstart/_index.md
content/en/docs/setup/install/multicluster.md

Fixed the path to the YAML files in the Quick Start example app to use `release_source_url` instead of `ghlink`. And, replaced the term "execute" with "run".

fix QS and replace term

---

content/en/docs/customize/externalLBs.md

Reverted External Load Balancers example to its version in the 1.3 docs, as per [VZ-8259](https://jira.oraclecorp.com/jira/browse/VZ-8259) Correct External Load Balancers example in our docs

revert external LB example

---

content/en/docs/reference/migration.md

This pull request adds a Multicluster section to the Deprecated API Migration Guide for APIs that will be removed in v2.0.0.

VZ-7315: Add section to Deprecated API Migration Guide for multicluster resources

---

content/en/docs/setup/install/multicluster.md

We made a change to the cluster label selector from syncRancherClsuters to syncClusters. Updating the docs for the same.

Changed the cluster selection from SyncRancherClusters to syncClusters

---

content/en/docs/setup/install/installation.md

This PR updates the kubectl get pods -n verrazzano-system output shown in the install guide.

Update kubectl get pods -n verrazzano-system output

---

config/_default/params.toml

Updated the Verrazzano version to 1.4.0.0.0 in private registry setup page for full distribution.

Fix the Verrazzano version in private registry setup page for full distribution

---

content/en/docs/customize/opensearch.md

Currently, the URLs that are used are no more pointing to the sections that we target, since the URLs are moved. Fixed them to point them to specific 2.3 release version links now.

VZ-8731: Fix URLs for OpenSearch plugin install section.

---

content/en/docs/customize/ingress.md
content/en/docs/customize/ociLoadBalancerIPs.md

Update ingress component name to ingressNGINX, as per JIRA [VZ-8505](https://jira.oraclecorp.com/jira/browse/VZ-8505) Examples in customize oci Loadbalancer ingress compoment name should be ingressNGNX

update ingress component name

---

content/en/docs/customize/ingress.md
content/en/docs/customize/ociLoadBalancerIPs.md

Backport of update ingress component name to ingressNGINX, as per JIRA [VZ-8505](https://jira.oraclecorp.com/jira/browse/VZ-8505) Examples in customize oci Loadbalancer ingress compoment name should be ingressNGNX

update ingress component name (#889)

---

content/en/docs/monitoring/tracing/jaeger-tracing.md

Add note and example for JIRA [VZ-8375](https://jira.oraclecorp.com/jira/browse/VZ-8375) Jaeger agent doesn't work with Helidon 3.x.

Add note and example for Helidon

---

content/en/docs/networking/traffic/net-traffic.md

Updates to multicluster traffic table as per [VZ-3812](https://jira.oraclecorp.com/jira/browse/VZ-3812) Need to document network port and protocol requirements for multicluster.

Fixes VZ-3812: Need to document network port and protocol requirements for multicluster

---

content/en/docs/monitoring/tracing/jaeger-tracing.md

Fixes JIRA VZ-8375 Jaeger agent doesn't work with Helidon 3.x. (#891)

---

content/en/docs/applications/traits/ingress/ingress.md

When using a custom certificate, you must create the TLS secret in the istio-system namespace, not in the application namespace.

VZ-8904 update doc to specify namespace for application certificate

---

content/en/docs/monitoring/tracing/jaeger-tracing.md
content/en/docs/reference/API/vpo-verrazzano-v1beta1.md
drafts/application-model/model/weblogic-domains.md

Reverts verrazzano/docs#916 since docs code is generated from api

Revert "elasticsearch to opensearch on Jaeger Tracing docs pages  (#915)"

---

assets/scss/_variables_project.scss
layouts/partials/navbar.html
layouts/shortcodes/blocks/cover.html

This PR merges the upstream changes to the Docsy theme to allow the navbar to be disabled on the Verrazzano homepage
The homepage now looks like the following:

Transparent nav bar can be disabled

---

content/en/docs/customize/ingress.md
content/en/docs/customize/ociLoadBalancerIPs.md

This PR updates the Verrazzano documentation to allow customization of oci-load-balancers using the `flexible` shape. Non-flex shapes are deprecated in May 2023

VZ-7460 Updating documentation for flexible LB shape

---

content/en/docs/quickstart/_index.md

As per VZ-9068, moved the CLI topic link (from the title to section content).

Backport: VZ-9068 move CLI link from title #953

---

content/en/docs/applications/_index.md
content/en/docs/backup/_index.md
content/en/docs/backup/argocd.md
content/en/docs/backup/keycloak.md
content/en/docs/backup/opensearch.md
content/en/docs/backup/rancher.md
content/en/docs/faq/_index.md
content/en/docs/guides/_index.md
content/en/docs/guides/ha/prod-upgrade.md
content/en/docs/monitoring/_index.md
content/en/docs/networking/_index.md
content/en/docs/reference/_index.md
content/en/docs/releasenotes/_index.md
content/en/docs/samples/_index.md
content/en/docs/security/_index.md
content/en/docs/setup/uninstall.md
content/en/docs/troubleshooting/_index.md
content/en/docs/uninstall/_index.md
content/en/docs/upgrade/_index.md
content/en/docs/upgrade/multicluster/_index.md
content/en/docs/upgrade/upgrade.md

- Moved Backup and Upgrade documentation out of uninstall folder
- Fixes to examples used in backup and restore documentation
- Added missing details to recover the currently documented components on a different cluster

VZ-9061 Backup and Restore documentation changes

---

content/en/docs/quickstart/_index.md

Moved CLI Setup link to the top of the section.

Backport to 1.5 - Moved CLI Setup link (#967)

---

content/en/docs/quickstart/_index.md

Moved CLI Setup link to the top of the section.

Backport to 1.4 - Moved CLI Setup link (#967)

---

assets/scss/_styles_project.scss
content/en/docs/access/_index.md
content/en/docs/backup/keycloak.md
content/en/docs/quickstart/_index.md
content/en/docs/samples/bobs-books.md
content/en/docs/samples/helidon-config/_index.md
content/en/docs/samples/hello-helidon/_index.md
content/en/docs/samples/sock-shop.md
content/en/docs/samples/spring-boot.md
content/en/docs/samples/standard-kubernetes.md
content/en/docs/samples/todo-list.md
content/en/docs/setup/install/cli-installation.md
content/en/docs/setup/install/kubectl-installation.md
content/en/docs/setup/install/mc-install/multicluster.md
content/en/docs/setup/install/modify-installation.md
content/en/docs/setup/platforms/Generic/generic.md
content/en/docs/setup/platforms/OCI/OCI.md
content/en/docs/setup/platforms/OLCNE/OLCNE.md
content/en/docs/setup/platforms/kind/kind.md
content/en/docs/troubleshooting/diagnostictools/analysisadvice/IngressInstallFailure.md
content/en/docs/troubleshooting/diagnostictools/analysisadvice/InstallFailure.md
content/en/docs/uninstall/uninstall.md
content/en/docs/upgrade/upgrade.md

Split installation guide into 2 documents, one using CLI other using kubectl.  There was a formatting problem due to the usage of tabs that really could only be resolved properly by discontinuing use of tabs. Docsy tab formatting interferes with hugo-dynamic-tabs as they both use underlying bootstrap tab panes but style them differently.
See before (right) / after (left):

Install Guide in 2 Pages vs. Tabs

---

content/en/docs/setup/install/kubectl-installation.md

Change verify install portion of kubectl based install to use kubectl instead of CLI.

kubectl instead of CLI for Verify Kubectl Install

---

layouts/404.html

Backport 1.5 - VZ: 9222 Updated link on 404 page #984

---

layouts/404.html

Backport 1.4 - VZ: 9222 Updated link on 404 page #984

---

layouts/404.html

Backport 1.3 - VZ: 9222 Updated link on 404 page #984

---

layouts/404.html

Backport 1.2 - VZ: 9222 Updated link on 404 page #984

---

layouts/404.html

Backport 1.1 - VZ: 9222 Updated link on 404 page #984

---

content/en/docs/releasenotes/_index.md
content/en/docs/setup/prereqs.md

This PR updates the document to set the correct versions of WebLogic Kubernetes Operator and WebLogic Monitoring Exporter.

Update WebLogic Kubernetes Operator and WebLogic Monitoring Exporter versions

---

content/en/docs/releasenotes/_index.md
content/en/docs/setup/prereqs.md

This PR updates the document to set the correct versions of WebLogic Kubernetes Operator and WebLogic Monitoring Exporter, in release-1.5 documentation.

Update WebLogic Kubernetes Operator and WebLogic Monitoring Exporter versions in release-1.5

---

content/en/docs/customize/externalLBs.md

Added mandatory statement to doc, as per [VZ-9325](https://jira.oraclecorp.com/jira/browse/VZ-9325) External IPs must be mandatory when using NodePort

add note for mandatory external IPs

---

content/en/docs/backup/keycloak.md

This change backports https://github.com/verrazzano/docs/pull/1043 to release-1.5, to fix backup and restore instructions for Keycloak

VZ-8888: Update Keycloak backup and restore instructions, release-1.5

---

content/en/docs/setup/private-registry/private-registry-full-distribution.md
content/en/docs/setup/private-registry/private-registry.md

The `jq` command to get the Rancher Agent image was wrong, it returned no images. This PR fixes the command.

Fix bad Rancher jq command

---

content/en/docs/setup/private-registry/private-registry-full-distribution.md
content/en/docs/setup/private-registry/private-registry.md

This PR includes:
- Simplified instructions in the "loading images" section (several bullet items removed)
- Added Rancher Agent to the list of images that needs to be public
- Added a section for WebLogic applications

VZ-9545: Updates to private registry pages

---

content/en/docs/setup/prereqs.md

Compute requirements for dev and prod profiles are incorrect https://verrazzano.io/devel/docs/setup/prereqs/.
dev profile
1. Each node should have at least 16GB memory instead of 8GB.
2. Each node should have 100 GB of disk storage instead of 30GB.
prod profile
1. Each node should have at least 4 CPUs instead of 2 CPUs.
2. Each node should have at least 32GB memory instead of 24GB.
3. Each node should have 100 GB of disk storage instead of 30GB.

VZ-9674: Documentation: compute requirements don't match the requirements validator webhook

---

content/en/docs/applications/oam/deploy-app.md
content/en/docs/guides/ha/prod-upgrade.md
content/en/docs/observability/logging/configure-opensearch/opensearch.md
content/en/docs/observability/logging/fluentd/_index.md
content/en/docs/observability/tracing/configure-tracing.md
content/en/docs/setup/access/console-urls.md
content/en/docs/setup/upgrade/verify.md

We still use es for default nodePool and pod names.

VZ-10008: Fix OS and OSD references

---

content/en/docs/releasenotes/_index.md

Rancher Partner charts and RKE2 charts removed from VZ Rancher 2.7.3

VZ-10058: Rancher Partner charts and RKE2 charts removed from VZ Rancher 2.7.3

---

content/en/docs/observability/monitoring/configure/thanos.md

Fix up the `storage.yaml` example in the Thanos doc

VZ-10077.  Update thanos Object Storage example for 1.6

---

config/_default/languages.toml
content/en/docs/troubleshooting/diagnostictools/analysisadvice/IngressInvalidShape.md

Fixed url.
Fixed hugo warning seen during execution of make target `hugo`
> WARN  config: languages.en.description: custom params on the language top level is deprecated and will be removed in a future release. Put the value below [languages.en.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120

Fixed url and hugo warning

---

content/en/docs/setup/upgrade/perform.md

Versions earlier than 1.4 are no longer supported. Removed command reflected a file name change that is now no longer relevant.

removed update to version prior to 1.4

---

content/en/docs/setup/upgrade/perform.md

Versions earlier than 1.4 are no longer supported.

removed update to version prior to 1.4 (#1206)

---

content/en/docs/observability/monitoring/configure/prometheus.md
content/en/docs/observability/monitoring/troubleshooting-prometheus.md

This PR adds the following Prometheus information:
1. A section on the Prometheus configuration page that describes how to configure data retention settings
2. A section on the Prometheus troubleshooting page describing how to recover from filling up persistent storage

VZ-10071: Add Prometheus storage information and troubleshooting

---

assets/scss/_variables_project.scss

Currently all headers have font-weight: 700 which makes h2, h3 looks awkward.  Reset font weights to theme font weights.
Before:
After:

Reset font weight of headers to theme font weight.

---

content/en/docs/troubleshooting/diagnostictools/analysisadvice/KontainerDriverNotReady.md

This pull request adds a runbook referenced from `vz analyze` for KontainerDriver resources not ready.

VZ-10276: add analyze of KontainerDriver resources

---

content/en/docs/_index.md

Hide doc archive page, as per [VZ-9735](https://jira.oraclecorp.com/jira/browse/VZ-9735) Documentation Archive page is no longer needed.

hide archive page

---

config/_default/config.toml
content/en/docs/_index.md
content/en/docs/setup/install/prepare/prereqs.md

Remove x-refs to the Archive page from the Doc home page and from the Documentation version menu.

remove-x-refs-to-archive-page-VZ-9735

---

content/en/docs/troubleshooting/diagnostictools/analysisadvice/ClusterApiClusterNotReady.md
content/en/docs/troubleshooting/diagnostictools/analysisadvice/KontainerDriverNotReady.md

This pull request adds a new runbook that is referenced by vz analyze when a cluster API cluster resource is not ready.
When a troubleshooting guide is available for CAPI created clusters this runbook should be updated to refer to that guide.

VZ-10278: add vz analyze runbook for cluster API resource not ready

---

content/en/docs/setup/upgrade/prepare.md

This change updates the application restart section of Prepare to Upgrade Verrazzano by specifying that weblogic workloads are only stopped for workloads that have an istio sidecar that is at least 2 versions out of date.

VZ-10297 correct weblogic restart documentation

---

config/_default/params.toml
content/en/docs/observability/monitoring/configure/prometheus.md
content/en/docs/observability/tracing/configure-tracing.md
layouts/shortcodes/jaeger_operator_helm_chart_version.html

Backport of Helm chart link changes to release-1.5. See https://github.com/verrazzano/docs/pull/1267 for details.
Note that Thanos was introduced in release 1.6 so the Thanos Helm chart link is not included in this PR.

Change Helm chart links to link to Verrazzano Helm charts (release-1.5)

---

content/en/docs/applications/oam/workloads/weblogic/_index.md

Get rid of outdated references to deprecated WLS version and domain home source type and add cross-reference to the new Domain on PV functionality, as per [VZ-8782](https://jira.oraclecorp.com/jira/browse/VZ-8782) DOC domain in PV with Verrazzano.
Add cross-references to the relevant WKO documentation and to using the WKTUI, as recommended by Ryan E, Paul, and Bryan.

Update WebLogic Workload documentation for VZ-8782

---

content/en/docs/setup/install/prepare/platforms/kind/kind.md

As per [VZ-10385](https://jira.oraclecorp.com/jira/browse/VZ-10385) Update Kind Version in Documentation and [VZ-10384](https://jira.oraclecorp.com/jira/browse/VZ-10384) Metallb Instructions Don't Work on Kubernetes 1.26, updated the documentation accordingly.

update kind and metallb versions

---

assets/scss/_variables_project.scss

Mike G: Currently all headers have font-weight: 700 which makes h2, h3 looks awkward. Reset font weights to theme font weights.

Reset font weight of headers to theme font weight

---

content/en/docs/setup/private-registry/private-registry.md

- Backport to 1.6 release - Fixed jq commands - "jq command cannot be split into multiple lines, because the whole thing is single-quoted."
- 1.5 release is already fixed via PR 1302.

Backport Fixed jq commands

---

content/en/docs/observability/monitoring/configure/prometheus.md
content/en/docs/observability/storage.md
content/en/docs/security/keycloak/keycloak.md

As per VZ-10469 Customizing OpenSearch Persistence Page Not about OpenSearch, moved Customize Persistent Storage to a standalone location within Observability section.

Move Customize Persistent Storage doc

---

content/en/docs/troubleshooting/troubleshooting-clusterapi.md

Pull request to update kubectl commands to show CAPI log files using a label selector.

Update kubectl commands to show capi log files

---

content/en/docs/setup/install/prepare/platforms/OLCNE/vcn.md
content/en/docs/troubleshooting/troubleshooting-clusterapi.md

To hopefully make it clear that these are examples and shouldn't be copied wholesale, I've put the tables in sections that are collapsed by default. If you think that's too hidden, let me know.

Add example security rules for OCI VCNs

---

content/en/docs/setup/install/perform/profiles.md
content/en/docs/setup/modify-installation.md

As per VZ-7947 Clarify enabling/disabling of components in our docs, added information to Installation Profiles and Modify VZ Installations to clarify enabling/disabling of components.

add-clarification-to profiles

---

content/en/docs/examples/helidon-config/_index.md
content/en/docs/examples/microservices/sock-shop.md
content/en/docs/examples/microservices/spring-boot.md

This fixes some syntax issues I noticed that led to the host name not being properly displayed to the user.

Fix for json-path related errors in some of the docs

---

content/en/docs/_index.md
content/en/docs/help/_index.md

- Backport to 1.2 Release. 
- Updated as per VZ-10505.

Backport 1.2 - VZ-10505: Added Support/Help page (#1352)

---

content/en/docs/_index.md
content/en/docs/help/_index.md

- Backport to 1.1 release 
- Updated as per VZ-10505.

Backport 1.1 - VZ-10505: Added Support/Help page (#1352)

---

content/en/docs/setup/install/prepare/platforms/OCI/OCI.md

VCN native pod networking is now supported for Verrazzano. Update the note in the OKE platform setup docs.

Update note about VCN native pod networking

---

config/_default/params.toml
content/en/docs/setup/upgrade/kubernetes-upgrade.md

This PR addresses customer issues with a single node upgrade on OLCNE with Verrazzano installed. With these steps, users should be able to drain and upgrade single node clusters. I have also provided a small amount of info on multi-node clusters, but most of that information is covered in the linked documentation.

VZ-10560 Add information on Kubernetes upgrades with Verrazzano

---

content/en/docs/support/_index.md

Update the Release History table for the 1.6.5, 1.5.6, and 1.4.7 releases in the 1.3.docs.

Update the release history table

---

content/en/docs/support/_index.md

Update the Release History table for the 1.6.5, 1.5.6, and 1.4.7 releases in the 1.2 docs.

Update RH table

---

content/en/docs/support/_index.md

Update the Release History table for the 1.6.5, 1.5.6, and 1.4.7 releases in the 1.1 docs.

Update Release History table

---

content/en/docs/_index.md

After discussion with Dave C, Will Lyons, and the doc team, we decided to put the Release History table back on the archive branch so that it can be updated in one location and linked to from all previous doc releases. The latest doc release will retain this table (and it will be updated) in its current location on the Support Information page.

Update RH table on archive branch

---

content/en/docs/_index.md
content/en/docs/support/_index.md

Change to the Support Information page to x-ref the Release History table on the archive branch.

Update link to RH table

---

content/en/docs/reference/vao-clusters-v1alpha1.md
content/en/docs/reference/vao-oam-v1alpha1.md
content/en/docs/reference/vco-clusters-v1alpha1.md
content/en/docs/reference/vpo-verrazzano-v1alpha1.md
content/en/docs/reference/vpo-verrazzano-v1beta1.md

API Install Overrides how include the links to the corresponding Helm chart.

VZ-11099 regenerate the API reference to include helm chart links

---

content/en/docs/setup/install/prepare/platforms/kind/kind.md

Fixed the MetalLB version used with Kubernetes v1.26 in the Kind installation instructions

Update kind cluster instructions

---

content/en/docs/observability/monitoring/configure/thanos.md

Also add information on configuring the OCI Object Storage provider in Thanos. This is a backport of changes in #1454 to release-1.6.

Update Thanos version

---

Jenkinsfile

Have the Jenkinsfile specify the label so it will get an instance provisioned if one isn't running

Add specific label to doc build

---

content/en/docs/observability/logging/fluent-operator.md

Looks like this was a global search and replace issue. Fix the example Fluent Bit commands to use the correct secret name.

Fix typo in Fluent Bit commands

---

content/en/docs/guides/migrate/install/cert-manager/_index.md
content/en/docs/guides/migrate/integrate/cert-manager/_index.md

This PR converts the cert manager doc into install and integration sections. It cleans up some of the content and removes unnecessary things like examples that use nginx and prometheus as that is probably more appropriate for the sections for those components. I only have netpol in the integration sections because we don't have servicemonitors or podmonitors for cert-manager or fluent configuration that I know about.

Convert cert manager into an install and integration section

---

content/en/docs/guides/migrate/integrate/cert-manager/_index.md
content/en/docs/guides/migrate/integrate/istio/_index.md
content/en/docs/guides/migrate/integrate/nginx/_index.md
content/en/docs/guides/migrate/integrate/prometheus/_index.md

This change adds the placeholders back into the cert manager integration doc. It also removes references to fluentd from all the integration docs.

Add cert manager integration placeholders back in and remove fluentd references

---

content/en/docs/guides/migrate/install/weblogic/_index.md
content/en/docs/guides/migrate/integrate/weblogic/_index.md

This PR updates the WebLogic Operator migration pages.
- Moves the NetworkPolicy section from the install page to the integrate page
- Removes "Fluentd" from a heading in the integrate page

VZ-11732: Update to WKO Migration Pages

---

content/en/docs/guides/migrate/install/weblogic/_index.md
content/en/docs/guides/migrate/integrate/weblogic/_index.md

In the WebLogic Kubernetes Operator migration docs, moves the "Migrate OAM WebLogic applications to OCNE 2.0" section from the install page to the integrate page.

VZ-11732: WKO migration docs - move Migrate OAM section

---

content/en/docs/guides/migrate/integrate/istio/_index.md
content/en/docs/guides/migrate/integrate/prometheus/_index.md

Adds the following Istio information to the Prometheus integration page of the OCNE 2.0 migration documentation:
1. An AuthorizationPolicy to allow the authenticating proxy to forward traffic to the Prometheus UI
2. A Prometheus PodMonitor to scrape Istio Envoy sidecar metrics
Note that since we don't yet have a solution for the authenticating proxy, there is placeholder information in the AuthorizationPolicy that will need to be filled in later.

Add Istio information to the Prometheus integration page

---

content/en/docs/guides/migrate/integrate/cert-manager/_index.md
content/en/docs/guides/migrate/integrate/opensearch/_index.md
content/en/docs/guides/migrate/integrate/weblogic/_index.md

This PR adds the Prometheus integration information to the OpenSearch integration page.
Notes:
1. Verrazzano does not collect metrics for cert-manager and the WebLogic Kubernetes Operator, so I have removed the Prometheus titles from those integration pages
2. The Prometheus information for the Istio integration page is being added in PR #1582

Updates for Prometheus integration pages

---

content/en/docs/guides/migrate/integrate/istio/_index.md

Removes load-dump from a network policy, since it is related to mysql.
The verrazzano repo has references to load-dump, all in relation to mysql.

VZ-11751: Istio Network Policies Migration - load dump

---

content/en/docs/guides/migrate/integrate/oauth2-proxy/_index.md

The OAuth2 Proxy Integrate doc has a typo that results in certain URLs looking like this: `[...].nip.io.nip.io`. This PR removes the duplicate `.nip.io`'s.

VZ-11798: Fix .nip.io typo in OAuth2 Proxy Integrate doc
