- content/en/docs/setup/platforms/OLCNE/OLCNE.md
backport of changes to ix verrazzano spec references for OLCNE setup
> VZ-3559: fix verrazzano spec references for OLCNE setup (#273)

- content/en/docs/setup/install/customizing/dns.md
- content/en/docs/setup/install/installation.md
Cherry pick VZ-3358 Create install/uninstall jobs/pods in verrazzano-install namespace
> VZ-3358 cherry pick 

- content/en/docs/setup/upgrade/_index.md
Add instructions to wait for old platform operator termination before upgrading.
> VZ-3573.  Upgrade doc update

- content/en/docs/setup/upgrade/_index.md
This reverts commit 8913d28c481904ec58c9144e4d7d8a2052b14fb4.
> Revert changes for VZ-3573.

- content/en/docs/setup/platforms/OLCNE/OLCNE.md
Minor change to add verrazzano to list of DNS records
> OLCNE DNS Doc change

- content/en/docs/reference/API/OAM/LoggingTrait.md
For the new logging trait changes, we are documenting the API for the LoggingTrait CRD.
> LoggingTrait Documentation with Example

- content/en/docs/samples/multicluster/hello-helidon/_index.md
- content/en/docs/samples/multicluster/todo-list/_index.md
This pull request updates the multicluster todo-list and hello-helidon examples.  The examples were changed to not use the MultiClusterComponents and MultiClusterSecrets objects.
> Updates to doc for multicluster todo-list and hello-helidon examples

- content/en/docs/reference/API/Verrazzano/Verrazzano.md
This PR includes updates to the Verrazzano API to include the KialiComponent that enables or disables the installation of Kiali
> VZ-3342 update VZ API to include Kiali

- content/en/docs/guides/lift-and-shift/lift-and-shift.md
- content/en/docs/guides/lift-and-shift/mysql-oam.yaml
- content/en/docs/guides/lift-and-shift/vz-application-modified.yaml
- Fixes for - VZ-3431, VZ-3830, VZ-3831.
- Removed ApplicationConfiguration and tls prefix from MySQL Yaml.
- Updated vz-application-modified.yaml to include MySQL Verrazzano components.
- Updated Lift and shift instructions to do the necessary changes.
> Updated Lift and Shift instructions for To Do List application

- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/versions.md
Updated the Keycloak version to 15.0.2 and MySQL version to 8.0.26.
> Update Keycloak and MySQL versions

- content/en/docs/guides/app-deployment/application-deployment-guide.md
- content/en/docs/guides/lift-and-shift/lift-and-shift.md
- content/en/docs/monitoring/logs/_index.md
- content/en/docs/quickstart/_index.md
- content/en/docs/releasenotes/_index.md
- content/en/docs/samples/multicluster/hello-helidon/_index.md
- content/en/docs/samples/standard-kubernetes.md
- content/en/docs/setup/install/customizing/ingress.md
- content/en/docs/setup/install/installation.md
- content/en/docs/setup/install/multicluster.md
- content/en/docs/setup/platforms/kind/kind.md
- content/en/docs/setup/platforms/minikube/minikube.md
- content/en/docs/setup/upgrade/_index.md
- content/en/docs/troubleshooting/troubleshooting-application-deployment.md
- content/en/docs/troubleshooting/troubleshooting-multicluster.md
Homogenize code examples/samples.
> remove shell attribute

- content/en/docs/guides/app-deployment/application-deployment-guide.md
- content/en/docs/guides/lift-and-shift/lift-and-shift.md
- content/en/docs/monitoring/metrics/metrics.md
- content/en/docs/networking/traffic/net-traffic.md
- content/en/docs/quickstart/_index.md
- content/en/docs/setup/install/customizing/elasticsearch.md
- content/en/docs/setup/install/installation.md
- content/en/docs/setup/platforms/OLCNE/OLCNE.md
- content/en/docs/setup/platforms/kind/kind.md
- content/en/docs/setup/private-registry/private-registry.md
- content/en/docs/setup/upgrade/_index.md
- content/en/docs/setup/versions.md
More updates for showing what is sample output
> More updates for labeling sample output

- content/en/docs/setup/install/installation.md
- content/en/docs/troubleshooting/diagnostictools/analysisadvice/InstallFailure.md
Update the log command to include install changes
Command was tested on the latest platform operator
> Install log command updated for install changes

- content/en/docs/samples/spring-boot.md
In Spring Boot example/sample output
Thanks to @Prasad Shirodkar
> fix VZ spelling typo

- content/en/docs/setup/install/multicluster.md
Add instructions for registering multicluster using LetsEncrypt staging certificates
> VZ-4134 Add instructions for registering multiclsuter using LetsEncrypt staging certificates

- drafts/early-access.md
Signed-off-by: Prasad Shirodkar <prasad.shirodkar@oracle.com>
> Fixed typos in the word "Verrazzano"

- content/en/docs/setup/install/installation.md
Fix inconsistent install instructions as per VZ-4225: Inconsistent Install Instructions, in the master docs branch.
> fix inconsistent install instructions

- content/en/docs/setup/install/installation.md
Fix inconsistent install instructions in 1.0.x docs
> fix install instructions

- content/en/docs/quickstart/_index.md
- content/en/docs/setup/install/installation.md
New command copied from the installation guide to the quickstart quide.
> Update quick start command

- config/_default/params.toml
- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/versions.md
> vz-4328 update release notes for 1.1

- content/en/docs/_index.md
*Updated text for doc archive reference
> Update text for doc archive reference

- content/en/docs/_index.md
* Update text for doc archive reference
> Update text for doc archive reference (#345)

- build-redirects.sh
Creates redirects for the docs file structure, such that all pages (e.g., verrazzano.io/docs) will redirect to the `latest` version (verrazzano.io/latest/docs).
> Build redirect script

- content/en/docs/monitoring/logs/_index.md
- content/en/docs/monitoring/oci-logging/oci-logging.md
- content/en/docs/reference/API/Verrazzano/Verrazzano.md
The OCI Logging service integration is a new feature planned for the next minor release. This PR updates the documentation to describe how to use the feature.
> VZ-4138: Add OCI Logging integration feature documentation

- scripts/publish.sh
- Updated publish script to not to publish files to root
> - Updated publish script 

- content/en/docs/quickstart/_index.md
- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/install/installation.md
- content/en/docs/setup/prereqs.md
Rename, add Prerequisite requirements, and merge with Software Versions doc.
> prereq doc

- content/en/docs/quickstart/_index.md
- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/install/installation.md
- content/en/docs/setup/prereqs.md
Backport prereq doc changes to 1.1 doc branch
> prereq doc (#364)

- content/en/docs/quickstart/_index.md
- content/en/docs/setup/install/installation.md
- content/en/docs/setup/prereqs.md
New prereq doc for the 1.x release doc branch.
> new prereq doc

- content/en/docs/setup/upgrade/_index.md
Changed the version in the setup/upgrade section to 1.1.0
> upgrade version to 1.1.0

- content/en/docs/setup/upgrade/_index.md
Update the version on the setup/upgrade page in the release-1.1 branch to v1.1.0.
> upgrade version to 1.1.0 (#367)

- config/_default/params.toml
- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/prereqs.md
Signed-off-by: stshapir <steven.shapiro@oracle.com>
> Updating docs for 1.1.1 patch release notes + versions

- content/en/docs/releasenotes/_index.md
Signed-off-by: stshapir <steven.shapiro@oracle.com>
> Backporting docs for 1.1.1 patch release notes + versions (#374)

- content/en/docs/releasenotes/_index.md
Added known issue for k8s rancher
Signed-off-by: stshapir <steven.shapiro@oracle.com>
> updated release notes for 1.1.1

- content/en/docs/releasenotes/_index.md
Signed-off-by: stshapir <steven.shapiro@oracle.com>
> Backport release notes for 1.1.1 (#377)

- content/en/docs/reference/API/Verrazzano/Verrazzano.md
- content/en/docs/setup/customizing/dns.md
For https://jira.oraclecorp.com/jira/browse/VZ-3670 we have introduced 2 featutures
Private DNS
Instance principal support
This ticket will track the doc changes / updates to summarize this
> VZ-4666: Update docs for private dns support and instance principal

- content/en/docs/reference/API/Verrazzano/Verrazzano.md
- content/en/docs/setup/customizing/dns.md
For https://jira.oraclecorp.com/jira/browse/VZ-3670 we have introduced 2 featutures
Private DNS
Instance principal support 
This ticket will track the doc changes / updates to summarize this
> VZ-4666: Add dns related docs - do not merge 

- content/en/docs/reference/API/Verrazzano/Verrazzano.md
- content/en/docs/security/rbac/rbac.md
- content/en/docs/setup/customizing/dns.md
- content/en/docs/setup/install/profiles.md
- content/en/docs/setup/upgrade/_index.md
- layouts/shortcodes/release_version.html
Incorporate the release_version short code
> fix version numbers

- content/en/docs/reference/API/Verrazzano/Verrazzano.md
- content/en/docs/security/rbac/rbac.md
- content/en/docs/setup/install/customizing/dns.md
- content/en/docs/setup/install/profiles.md
- content/en/docs/setup/upgrade/_index.md
- layouts/shortcodes/release_version.html
Update release version to use a shortcode.
> update release version

- content/en/docs/guides/lift-and-shift/lift-and-shift.md
Back port PR to address doc bug 33152590
> add example assumption (#387)

- content/en/docs/guides/app-deployment/application-deployment-guide.md
As per Doc 33152524 - DOC UPDATE FOR “ACCESS THE APPLICATION’S METRICS”  and Doc 33160226 - UPDATE DOCUMENTATION ON HOW TO CONFIGURE DASHBOARDS FOR PROMETHEUS, KIBANA AND GRAFANA
> update app metrics and logs access info

- content/en/docs/reference/API/OAM/Workloads.md
Fix broken link from Verrazzano Workload Custom Resource Definitions to WKO Domain CRD doc.
> fix broken link to WKO domain resource doc

- content/en/docs/reference/API/OAM/Workloads.md
> fix broken link to WKO domain resource doc (#395)

- content/en/docs/reference/API/OAM/Workloads.md
Fix broken link to WKO domain CRD
> fix broken linkn to WKO domain CRD

- content/en/docs/setup/customizing/ociLoadBalancerIPs.md
Backport https://github.com/verrazzano/docs/pull/390
> VZ-4785 - Add new loadbalancer customizing docs

- content/en/docs/setup/customizing/ociLoadBalancerIPs.md
Minor edits to align doc style.
> minor edits

- content/en/docs/setup/customizing/ociLoadBalancerIPs.md
> minor edits (#399)

- content/en/docs/quickstart/_index.md
- content/en/docs/setup/customizing/certificates.md
- content/en/docs/setup/install/installation.md
Add note about self-signed certs.
> add note about self-signed certs

- content/en/docs/quickstart/_index.md
- content/en/docs/setup/customizing/certificates.md
- content/en/docs/setup/install/installation.md
Back port note about self-signed certs
> add note about self-signed certs (#401)

- content/en/docs/faq/FAQ.md
Back port FAQ fix to 1.1 docs.
> fix FAQ (#406)

- content/en/docs/samples/bobs-books.md
- content/en/docs/samples/helidon-config/_index.md
- content/en/docs/samples/hello-helidon/_index.md
- content/en/docs/samples/sock-shop.md
- content/en/docs/samples/spring-boot.md
- content/en/docs/samples/todo-list.md
> Revert "update helidon doc"

- content/en/docs/setup/prereqs.md
Add a section to the prerequisites page stating hardware requirements.
> No JIRA: Add hardware requirements

- content/en/docs/setup/prereqs.md
Add a section to the prerequisites page stating hardware requirements.
> No JIRA: Add hardware requirements (release 1.1)

- content/en/docs/setup/prereqs.md
Add a section to the prerequisites page stating hardware requirements.
> No JIRA: Add hardware requirements (release 1.0)

- content/en/docs/samples/bobs-books.md
- content/en/docs/samples/helidon-config/_index.md
- content/en/docs/samples/hello-helidon/_index.md
- content/en/docs/samples/sock-shop.md
- content/en/docs/samples/spring-boot.md
- content/en/docs/samples/todo-list.md
This reverts commit 442f43aea9e4238f3b75a352c24accc8e3f5ae5e. 
Update example docs to reflect the removal of namespaces from the yaml files
> Revert "Revert "update helidon doc (#405)" (#410)"

- content/en/docs/monitoring/metrics/metrics.md
This documentation addition describes the process of verifying the metrics template process by using the Prometheus console.
> VZ-4912 Describe Prometheus console interaction to verify metrics

- content/en/docs/quickstart/_index.md
PR to backport doc update to use new command to get VPO logs
> VZ-4578 change command to get VPO logs (#416)

- content/en/docs/setup/platforms/kind/kind.md
Update references in the doc to new version of MetalLB
Signed-off-by: Mark Nelson <mark.x.nelson@oracle.com>
> Update metal-lb refs to 0.11.0

- content/en/docs/samples/multicluster/_index.md
- content/en/docs/samples/multicluster/hello-helidon/_index.md
- content/en/docs/samples/multicluster/sock-shop/_index.md
- content/en/docs/samples/multicluster/todo-list/_index.md
Change index page for multicluster examples. Aligns better with other examples and other docs.
> change index page for mc examples

- content/en/docs/setup/customizing/ociLoadBalancerIPs.md
Documents how to override the subnet placement for VZ load balancers for private LB configurations.
> VZ-5064. Update Customizing OKE LBs doc

- config/_default/params.toml
- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/prereqs.md
Updates to public docs for v1.1.2 on release-1.1 branch
> VZ-5229: VERRAZZANO 1.1.2 PATCH RELEASE

- content/en/docs/samples/helidon-config/_index.md
- content/en/docs/samples/hello-helidon/_index.md
- content/en/docs/samples/multicluster/sock-shop/_index.md
- content/en/docs/samples/multicluster/todo-list/_index.md
- content/en/docs/samples/sock-shop.md
- content/en/docs/samples/spring-boot.md
- content/en/docs/samples/todo-list.md
Remove References to Variety of URLs in Example Docs as per [VZ-5257](https://jira.oraclecorp.com/jira/browse/VZ-5257).
> remove endpoint URLs

- content/en/docs/applications/workloads/weblogic/_index.md
- content/en/docs/guides/app-deployment/application-deployment-guide.md
- content/en/docs/guides/lift-and-shift/lift-and-shift.md
- content/en/docs/quickstart/_index.md
- content/en/docs/reference/API/OAM/IngressTrait.md
- content/en/docs/samples/bobs-books.md
- content/en/docs/samples/helidon-config/_index.md
- content/en/docs/samples/hello-helidon/_index.md
- content/en/docs/samples/sock-shop.md
- content/en/docs/samples/spring-boot.md
- content/en/docs/samples/todo-list.md
Reference Custom Resources By Full Name as per [VZ-5255](https://jira.oraclecorp.com/jira/browse/VZ-5255).
> replace with CRD full name

- content/en/docs/applications/workloads/weblogic/_index.md
- content/en/docs/guides/app-deployment/application-deployment-guide.md
- content/en/docs/guides/lift-and-shift/lift-and-shift.md
- content/en/docs/quickstart/_index.md
- content/en/docs/reference/API/OAM/IngressTrait.md
- content/en/docs/samples/bobs-books.md
- content/en/docs/samples/helidon-config/_index.md
- content/en/docs/samples/hello-helidon/_index.md
- content/en/docs/samples/sock-shop.md
- content/en/docs/samples/spring-boot.md
- content/en/docs/samples/todo-list.md
Backport Reference Custom Resources By Full Name as per [VZ-5255](https://jira.oraclecorp.com/jira/browse/VZ-5255)
> replace with CRD full name (#435)

- content/en/docs/releasenotes/_index.md
* Add release notes for 1.2.0 release
> Backport Release notes for v1.2.0 from master

- content/en/docs/setup/upgrade/_index.md
Update the upgrade doc as per [VZ-5252](https://jira.oraclecorp.com/jira/browse/VZ-5252) Upgrade Documentation Clarification and [VZ-5253](https://jira.oraclecorp.com/jira/browse/VZ-5253) Restart Upgrade Documentation.
> update VZ upgrade

- content/en/docs/setup/upgrade/_index.md
Backport Upgrade updates to the 1.1 docs
> update VZ upgrade (#437)

- content/en/docs/access/_index.md
- content/en/docs/access/console/_index.md
- content/en/docs/monitoring/logs/_index.md
- content/en/docs/monitoring/metrics/metrics.md
- content/en/docs/samples/helidon-config/_index.md
- content/en/docs/samples/hello-helidon/_index.md
- content/en/docs/samples/multicluster/sock-shop/_index.md
- content/en/docs/samples/multicluster/todo-list/_index.md
- content/en/docs/samples/sock-shop.md
- content/en/docs/samples/spring-boot.md
- content/en/docs/samples/todo-list.md
- content/en/docs/setup/install/installation.md
- content/en/docs/setup/install/multicluster.md
Backport Access URL change to the 1.1 docs.
> backport changes to 1.1 docs

- content/en/docs/setup/prereqs.md
Backport updated Release Table dates and Installed Component versions.
> backport updated prereqs

- content/en/docs/setup/prereqs.md
Backport fix release date to 1.2 docs
> fix date (#452)

- content/en/docs/quickstart/_index.md
- content/en/docs/setup/install/installation.md
- content/en/docs/setup/upgrade/_index.md
- layouts/shortcodes/release_asset_url.html
Fix platform operator update to the latest version command (remove new line) and replace the command to get the logs.
> fix commands

- content/en/docs/quickstart/_index.md
- content/en/docs/setup/install/installation.md
- content/en/docs/setup/upgrade/_index.md
- layouts/shortcodes/release_asset_url.html
* fix commands
* fix newline shortcode
* fix name change
> fix commands (#454)

- content/en/docs/access/_index.md
- content/en/docs/access/console/_index.md
- content/en/docs/monitoring/logs/_index.md
- content/en/docs/samples/helidon-config/_index.md
- content/en/docs/samples/hello-helidon/_index.md
- content/en/docs/samples/multicluster/sock-shop/_index.md
- content/en/docs/samples/multicluster/todo-list/_index.md
- content/en/docs/samples/sock-shop.md
- content/en/docs/samples/spring-boot.md
- content/en/docs/samples/todo-list.md
- content/en/docs/setup/install/installation.md
- content/en/docs/setup/install/multicluster.md
Change the Access URL in the 1.1 docs
> change access URL

- content/en/docs/reference/API/Verrazzano/Verrazzano.md
- content/en/docs/setup/customizing/opensearch.md
Documents node storage API for 1.3
> VZ 5913: node storage

- content/en/docs/quickstart/_index.md
* VZ-5031: Update dev profile to use persistent storage by default
* VZ-5031: Update dev profile to use persistent storage by default
> VZ-5031: Update dev profile to use persistent storage by default (#461)

- content/en/docs/setup/upgrade/_index.md
Reword the Istio proxy section.  Remove upgrade failed section since upgrade will never go into a failed state.
> VZ-5381 minor upgrade doc change for 1.3

- content/en/docs/setup/upgrade/_index.md
Document the UpgradePaused state behavior
> VZ-5381 upgrade doc

- content/en/docs/reference/API/Verrazzano/Verrazzano.md
- content/en/docs/setup/prereqs.md
This PR introduces the Prometheus Operator component in the documentation. Further documentation about use and features will follow once they are implemented.
> VZ-5305 Prometheus Operator component addition

- content/en/docs/reference/API/Verrazzano/MetricsTemplate.md
This pull request includes changes recently made to the standard-k8s-metrics-template MetricsTemplate.
> VZ-5362: Update documented standard-k8s-metrics-template

- content/en/docs/reference/API/Verrazzano/MetricsTemplate.md
Backport to release-1.2 to update documented standard-k8s-metrics-template
> VZ-5362: update documented standard-k8s-metrics-template (#471)

- content/en/docs/reference/API/Verrazzano/Verrazzano.md
- content/en/docs/setup/prereqs.md
Add basic information for the Prometheus Adapter.
> VZ-5539: Add Prometheus Adapter information

- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/prereqs.md
Update release notes for 1.2.1
> VZ-5754 - Update release notes for 1.2.1

- content/en/docs/monitoring/tracing/jaeger-tracing.md
- content/en/docs/reference/API/Verrazzano/Verrazzano.md
Documents the Jaeger Operator Verrazzano component.
> VZ 5620: Document Jaeger Operator

- content/en/docs/monitoring/tracing/jaeger-tracing.md
- content/en/docs/reference/API/Verrazzano/Verrazzano.md
Document configuration required to integrate Istio with Jaeger tracing.
> VZ 5802: Document Jaeger/Istio integration

- content/en/docs/reference/API/OAM/IngressTrait.md
Backport of doc for ingress trait destination HTTP cookie to the release-1.2 branch.
> VZ-5672: Add ingress trait HTTP cookie information (release-1.2)

- content/en/docs/applications/_index.md
Document the cluster role privileges for the OAM operator.
> VZ-4969: Document the set of default OAM operator privileges

- content/en/docs/monitoring/_index.md
- content/en/docs/monitoring/logs/_index.md
- content/en/docs/monitoring/metrics/metrics.md
- content/en/docs/monitoring/oci-logging/oci-logging.md
- content/en/docs/monitoring/tracing/jaeger-tracing.md
> reorder sections

- content/en/docs/setup/platforms/OLCNE/OLCNE.md
small change to add information bout editing the kube-controller-manager manifest
> NOJIRA: Add info about editing the kube-controller-manager manifest

- content/en/docs/setup/prereqs.md
This pull request updates the version of WebLogic Kubernetes Operator in the prereqs.
> Update wko version

- content/en/docs/reference/API/Verrazzano/Verrazzano.md
- content/en/docs/setup/customizing/externalLBs.md
- content/en/docs/setup/install/multicluster.md
- add type and ports to istio ingress
- add custom install guide for external load balancer
- fix preregistration setup for managed cluster with LetsEncrypt staging
> external load balancers

- content/en/docs/reference/API/OAM/IngressTrait.md
Updated the reference to include information about the new authorization policy and related resources APIs
> JIRA: VZ-5946 Update ingress trait reference to include authorization policy info

- content/en/docs/reference/API/Verrazzano/Verrazzano.md
- content/en/docs/setup/customizing/ingress.md
- content/en/docs/setup/customizing/istio.md
This change updates VZ CRD API and the ingress and istio customize installation page to include information about install overrides.
> VZ-5702: Update API, ingress, and istio pages with overrides documentation

- content/en/docs/reference/API/Verrazzano/Verrazzano.md
- content/en/docs/setup/customizing/ingress.md
Backport of Overrides doc changes
> VZ-5702 overrides backport

- content/en/docs/troubleshooting/troubleshooting-multicluster.md
Backporting Multicluster troubleshooting documentation updates to the release-1.3 branch.
> VZ-6184 Update to Multicluster Troubleshooting documentation (#520)

- content/en/docs/reference/API/Verrazzano/Verrazzano.md
Update wording for overrides documentation based on feedback
> No Jira: Change wording for precedence

- content/en/docs/reference/API/Verrazzano/Verrazzano.md
No Jira: Change wording for precedence
(cherry picked from commit 00a998a7472f6a46997e7bb0a666899d9dbd484c)
> Backport Overrides doc changes

- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/prereqs.md
- Updated the docs for Verrazzano patch release 1.3.1
> Verrazzano patch release 1.3.1

- content/en/docs/reference/API/Verrazzano/Verrazzano.md
(cherry picked from commit 41b3d3ad344a242ce31614cbc8f289541949f974)
> Backport of link fix in reference documentation

- content/en/docs/setup/customizing/externalLBs.md
- content/en/docs/setup/platforms/OLCNE/OLCNE.md
Updated the doc after manually installing olcne and verrazzano in OCI
> update install instruction on olcne

- content/en/docs/setup/cli/_index.md
- content/en/docs/setup/customizing/_index.md
- content/en/docs/setup/install/_index.md
- content/en/docs/setup/private-registry/private-registry.md
- content/en/docs/setup/uninstall/uninstall.md
- content/en/docs/setup/upgrade/_index.md
Setup/install the Verrazzano CLI.
> first draft for CLI setup

- content/en/docs/setup/uninstall/uninstall.md
Add a note saying that uninstall will not delete applications.
> VZ-6292 delete apps note for uninstall

- content/en/docs/quickstart/_index.md
- content/en/docs/setup/cli/_index.md
Revised Quick Start guide to use CLI.
> revised quick start using CLI

- content/en/docs/setup/install/installation.md
Revised installation procedure to add using CLI.
> installation using CLI

- content/en/docs/setup/uninstall/uninstall.md
> CLI uninstall instructions

- content/en/docs/reference/API/Verrazzano/Verrazzano.md
Backport CR doc fix to latest release.
> fix doc (#543)

- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/customizing/prometheus.md
This PR adds a page to the setup customization section for Prometheus.
> NO JIRA: Add customizing Prometheus page

- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/prereqs.md
Verrazzano release notes for patch release - 1.3.2
> Release notes for v1.3.2

- config/_default/params.toml
- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/prereqs.md
This PR backports Verrazzano release notes for patch release - 1.3.2 to release-1.3 branch
> Backport release notes for v1.3.2

- content/en/docs/setup/platforms/OLCNE/OLCNE.md
The guide for deploying Verrazzano 1.2 on OCNE should account for the addition of the oci-csi storage driver in OCNE 1.4.  References to manual storage setup using NFS and manual creation of persistent volumes has been eliminated.
> Update 1.2 on OLCNE 1.4 docs to account for oci-csi driver

- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/prereqs.md
> Release notes for v1.3.3

- config/_default/params.toml
- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/prereqs.md
> Scchen/release 1.3.3 backport

- content/en/docs/guides/sidecar/_index.md
- content/en/docs/setup/platforms/OLCNE/OLCNE.md
Minor doc change with regard to headings.
> minor doc edits

- content/en/docs/setup/customizing/ha.md
Add a "High Availability" sub-section to Customize Installations
> VZ-6425: Add HA section under customize installations

- content/en/docs/quickstart/_index.md
- content/en/docs/setup/uninstall/uninstall.md
Update the uninstall doc to reflect the new uninstall behavior.
> VZ-6681 update uninstall doc

- content/en/docs/setup/customizing/ha.md
Add some guidelines for resources required to perform an HA install.
> VZ-6425: Add resource requirements for HA install

- content/en/docs/setup/uninstall/uninstall.md
> Minor uninstall doc fixes

- content/en/docs/setup/prereqs.md
Add End of Error Correction dates to Prereqs doc.
> update VZ dates

- content/en/docs/setup/prereqs.md
* update VZ dates
* incorporate Mike's edits
> update VZ dates (#572)

- content/en/docs/setup/backup/_index.md
- content/en/docs/setup/backup/backup.md
- content/en/docs/setup/backup/prerequisites.md
- content/en/docs/setup/backup/restore.md
Incorporate edits from Kevin M. Still others to discuss
[Backup&Recovery.docx](https://github.com/verrazzano/docs/files/9351978/Backup.Recovery.docx)
.
> cleanup backup and restore

- content/en/docs/guides/app-deployment/application-deployment-guide.md
- content/en/docs/quickstart/_index.md
Add docs to optionally suppress warnings that do not impact functionality
> VZ-5572 Suppress Kiali Console Warnings

- content/en/docs/setup/install/profiles.md
Fix replica count for opensearch prod profile
> VZ-6791 fix replica count for opensearch prod profile

- content/en/docs/setup/install/profiles.md
Fix replica count for opensearch prod profile (cherry-pick from master)
> fix replica count for opensearch prod profile (#581)

- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/prereqs.md
> VZ-6678 Rancher 2.6.7 updates

- content/en/docs/reference/API/Verrazzano/v1alpha1.md
- content/en/docs/reference/API/Verrazzano/v1beta1.md
- content/en/docs/setup/customizing/grafana.md
Add doc for the configuration of a database for Grafana
> VZ-6723: Document the configuration of a database for Grafana

- content/en/docs/reference/API/Verrazzano/v1alpha1.md
- content/en/docs/reference/API/Verrazzano/v1beta1.md
Add API definition for MySQLOperator component
Also fixed a bunch of warnings my IDE gave about tables missing a closing "|"
> VZ-6807: add api changes for MySQLOperator component

- content/en/docs/setup/prereqs.md
The pull request updates the  WKO version used by Verrazzano.
> VZ-6938: update WKO version used by Verrazzano

- content/en/docs/setup/prereqs.md
Update formatting and add backup operators info
> Update backup operators info

- content/en/docs/releasenotes/_index.md
Hello, 
Updated the Release Notes page - an impact of update in https://github.com/verrazzano/docs/pull/594. 
Please verify. 
Thank you.
> Added Component updates, impact from VZ-6988

- content/en/docs/setup/prereqs.md
Doc formatted. 
Moved the new additions to be listed in alphabetic order. No content/text change.
> Doc formatting changes

- content/en/docs/guides/ha/node-failure.md
- content/en/docs/guides/sidecar/_index.md
This is a complicated to read doc. Tried my best to clarify where possible. Believe I fixed the formatting but was unhappy to see that the shortcodes were not recognized. (If I see this again, I'll try to get it fixed.) Please review for technical accuracy and that I did not change anything you disagree with. If so, provide me the edits and I'll incorporate them.
> add node failure guide

- content/en/docs/guides/ha/_index.md
- content/en/docs/guides/ha/node-failure.md
- content/en/docs/reference/migration.md
- content/en/docs/setup/customizing/grafana.md
Some cleanup and created a new section for HA topics
> some minor edits

- content/en/docs/releasenotes/_index.md
Removed Fluentd and MySQL entries.
> Updated Release Notes

- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/prereqs.md
> VZ-6949 Rancher 2.6.8 update

- content/en/docs/guides/ha/_index.md
- content/en/docs/guides/ha/node-failure.md
- content/en/docs/guides/ha/prod-upgrade.md
Add guide for upgrading from prod to HA
> VZ-7005 Add guide for upgrading from prod to HA

- content/en/docs/quickstart/_index.md
- content/en/docs/setup/private-registry/private-registry-full-distribution.md
- content/en/docs/setup/private-registry/private-registry.md
IMO, it makes more logical sense to present the introductory topics this way.
> revise content flow

- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/prereqs.md
Updated from jaeger to jaeger operator, added istio version updates
> Updated from jaeger to jaeger operator, added istio version updates

- content/en/docs/monitoring/oci-logging/oci-logging.md
- content/en/docs/setup/install/multicluster.md
- content/en/docs/setup/private-registry/private-registry-full-distribution.md
- content/en/docs/uninstall/backup/backup.md
- content/en/docs/uninstall/backup/prerequisites.md
- content/en/docs/uninstall/backup/restore.md
@gilbode expressed a degree of displeasure with our (over) use of tabs. I removed them from some docs and am interested in your feedback about whether it's an improvement or not. Also, please check your docs to make sure that the text and procedural flow was not incorrectly interrupted. Thank you.
> remove tabs in some docs

- content/en/docs/monitoring/oci-logging/oci-logging.md
- content/en/docs/networking/security/net-security.md
- content/en/docs/quickstart/_index.md
- content/en/docs/setup/install/installation.md
- content/en/docs/setup/platforms/OLCNE/OLCNE.md
- content/en/docs/setup/prereqs.md
- content/en/docs/uninstall/uninstall.md
Minor fix to change two subsection headings that were the same, therefore, interfering with their subsection links.
> fix redundant headings

- content/en/docs/customize/certificates.md
- content/en/docs/setup/install/installation.md
- content/en/docs/setup/install/profiles.md
- content/en/docs/setup/prereqs.md
* modify note as per Dave C
* fix cert-manager
> modify note as per Dave C (#637)

- .latest
> no longer latest

- content/en/docs/setup/prereqs.md
> add Jaeger (#645)

- content/en/docs/setup/cli/_index.md
- layouts/shortcodes/release_asset.html
- layouts/shortcodes/release_asset_url.html
New CLI instructions work as expected
> CLI setup doc change

- content/en/docs/customize/ha.md
Adding 2 additional HA configurations
> Updating HA example docs

- config/_default/params.toml
- content/en/docs/setup/private-registry/private-registry.md
This PR updates the instructions for setting up private registry, by obtaining the cumulative patches from "My Oracle Support"
> Update instructions for private registry setup for cumulative patches

- content/en/docs/guides/ha/prod-upgrade.md
Minor fixes to the upgrade prod install to HA page
> Minor fixes to the upgrade prod install to HA page

- content/en/docs/releasenotes/_index.md
Release notes for 1.3.6 patch release containing fix for bug VZ-7190
> Added Release notes for v1.3.6 patch release

- content/en/docs/reference/API/OAM/IngressTrait.md
This PR updates the rules for hostname in ingress-trait
> Updated rules regarding hostname in ingresstrait

- content/en/docs/reference/API/OAM/IngressTrait.md
Backport the changes made to master
> VZ-3603:Backporting the updated rules regarding ingress trait

- config/_default/params.toml
- content/en/docs/releasenotes/_index.md
> Backport release-1.4.1 notes

- content/en/docs/reference/API/Verrazzano/v1alpha1.md
- content/en/docs/reference/API/Verrazzano/v1beta1.md
Update the description of the Overrides in VZ API doc
> update Overrides description

- DEVELOPMENT.md
This pull request documents the steps for updating the generated API reference documentation.
> Documentation to update generated API reference documentation 

- config/_default/params.toml
> update 1.3.6 to 1.3.7

- content/en/docs/setup/prereqs.md
WKO docs re-organized, changed this link.
> fix link to WKO prereqs

- content/en/docs/reference/API/vpo-verrazzano-v1alpha1.md
- content/en/docs/reference/API/vpo-verrazzano-v1beta1.md
all changes are resulting from `make generate-api BRANCH=master`
> VZ-7726 Update the API resources for cluster operator

- content/en/docs/reference/API/OAM/MetricsTrait.md
> add ports and portspec

- content/en/docs/quickstart/_index.md
Backport Quick Start file path fix
> edit path to example files (#707)

- content/en/docs/monitoring/metrics/metrics.md
- content/en/docs/samples/todo-list.md
- content/en/docs/setup/install/multicluster.md
- content/en/docs/uninstall/backup/backup.md
- content/en/docs/uninstall/backup/restore.md
Remove the term 'execute' from the master docs.
> remove the term execute

- content/en/docs/_index.md
Edit version listing on Doc Archive page
> edit version listing

- content/en/docs/customize/ociLoadBalancerIPs.md
Fixed identation for error converting YAML to JSON: yaml: line 10: mapping values are not allowed in this context
> Fixed identation for error converting YAML to JSON: yaml: line 10: mapping values are not allowed in this context

- content/en/docs/customize/authproxy.md
- content/en/docs/customize/certificates.md
- content/en/docs/customize/dns.md
- content/en/docs/customize/grafana.md
- content/en/docs/customize/ingress.md
- content/en/docs/customize/istio.md
- content/en/docs/customize/ociLoadBalancerIPs.md
- content/en/docs/customize/opensearch.md
- content/en/docs/customize/prometheus.md
- content/en/docs/customize/storage.md
- content/en/docs/samples/bobs-books.md
- content/en/docs/samples/hello-helidon/_index.md
- content/en/docs/samples/multicluster/hello-helidon/_index.md
- content/en/docs/samples/multicluster/sock-shop/_index.md
- content/en/docs/samples/multicluster/todo-list/_index.md
- content/en/docs/samples/sock-shop.md
- content/en/docs/samples/spring-boot.md
- content/en/docs/samples/todo-list.md
- content/en/docs/uninstall/backup/backup.md
Backported the changes to 1.4 release.
> Backport-Doc-feedback-fixes-734

- content/en/docs/setup/install/profiles.md
This PR updates the list of components in the profile documentation, ensures that the component names follow the public API component names, and alphabetizes the components.
> VZ-7834: Update Enabled Components for Each Profile

- content/en/docs/troubleshooting/diagnostictools/analysisadvice/IstioIngressGatewayNoLoadBalancerIP.md
- content/en/docs/troubleshooting/diagnostictools/analysisadvice/IstioLoadBalancerCreationIssue.md
- content/en/docs/troubleshooting/diagnostictools/analysisadvice/NginxLoadBalancerCreationIssue.md
We have seen failure while creating loadbalancer for istio ingress gateway because no public subnets are available.
This runbook will take care of that.
> VZ-7368: runbook for istio loadbalancer issue

- content/en/docs/customize/storage.md
Note the persistent storage is required for MySQL
> VZ-8000: Note the persistent storage is required for MySQL

- content/en/docs/customize/opensearch.md
- content/en/docs/reference/API/vpo-verrazzano-v1alpha1.md
- content/en/docs/reference/API/vpo-verrazzano-v1beta1.md
Added Documentation to provide the information about the non_bundled OS/OSD plugin installation.
> VZ-7841: Document non_bundled OS plugin support

- content/en/docs/customize/opensearch.md
PR to add more information about ISM policy created through Verrazzano.
> VZ-7908: Add more details for ISM policy support by Verrazzano

- content/en/docs/customize/opensearch.md
- content/en/docs/reference/API/Verrazzano/v1alpha1.md
- content/en/docs/reference/API/Verrazzano/v1beta1.md
document support for OS/OSD plugin installation in release 1.4
> VZ-7841: back port document support for OS/OSD plugin installation to release 1.4

- assets/scss/_styles_project.scss
- config/_default/config.toml
- layouts/partials/navbar.html
Backporting version dropdown menu for v1.4
> Vz dropdown menu backport1.4

- assets/scss/_styles_project.scss
- config/_default/config.toml
- layouts/partials/navbar.html
> Revert "Vz dropdown menu backport1.4"

- assets/scss/_styles_project.scss
- config/_default/config.toml
- layouts/partials/navbar.html
> Revert "Abehern/vz 7299 add a vz release menu to the open source documenation landing page"

- content/en/docs/setup/prereqs.md
Updates version of various components installed by Verrazzano in release-1.4
> Update version of various components installed by Verrazzano in release-1.4

- content/en/docs/setup/prereqs.md
Updates version of various components installed by Verrazzano
> Update version of various components installed by Verrazzano

- content/en/docs/customize/opensearch.md
- content/en/docs/setup/install/profiles.md
- content/en/docs/setup/platforms/OLCNE/OLCNE.md
- content/en/docs/setup/prereqs.md
Backport numbers fix to the 1.4 docs
> Fix numbers and units of measure (#771)

- assets/scss/_styles_project.scss
- config/_default/config.toml
- config/_default/params.toml
- layouts/partials/navbar.html
Remove "Releases" label and only display menu on docs page
> Vz dropdown menu backport1.3

- assets/scss/_styles_project.scss
- config/_default/config.toml
- config/_default/params.toml
- layouts/partials/navbar.html
Remove "Releases" label and only display menu on docs page
> Vz dropdown menu backport1.2

- assets/scss/_styles_project.scss
- config/_default/config.toml
- config/_default/params.toml
- layouts/partials/navbar.html
Remove "Releases" label and only display menu on docs page
> Vz dropdown menu backport1.1

- content/en/docs/access/_index.md
Updating the `vz status` command to be consistent with its output in Verrazzano.
> Updating status command in docs

- content/en/docs/setup/cli/_index.md
Changed the word "executed" to "run".
> Change word

- content/en/docs/reference/API/vao-oam-v1alpha1.md
- content/en/docs/reference/API/vco-clusters-v1alpha1.md
- content/en/docs/reference/API/vpo-verrazzano-v1alpha1.md
- content/en/docs/reference/API/vpo-verrazzano-v1beta1.md
- scripts/genapidocs/config.json
This pull request updates the generated API reference docs to reflect the latest APIs from the master branch.
> Update generated API reference doc to reflect latest APIs

- content/en/docs/customize/externalLBs.md
* revert external LB example
* Change ingress to ingressNGINX
> revert external LB example (#791)

- content/en/docs/troubleshooting/troubleshooting-mysql.md
- content/en/docs/troubleshooting/troubleshooting-prometheus.md
Add troubleshooting page for MySQL
> VZ-7514: Add troubleshooting page for MySQL

- content/en/docs/monitoring/logs/_index.md
- content/en/docs/releasenotes/_index.md
> Minor Fixes

- content/en/docs/setup/install/installation.md
Backport of #822 to release-1.5
> Update kubectl get pods -n verrazzano-system output (#822)

- content/en/docs/customize/ingress.md
Signed-off-by: Ali Mukadam <ali.mukadam@oracle.com>
> docs: typo in customize ingress controller section

- content/en/docs/reference/API/vao-oam-v1alpha1.md
- content/en/docs/reference/API/vco-clusters-v1alpha1.md
This pull request regenerates the v1.5.0 API docs which were not up-to-date.
> Update 1.5 api docs

- content/en/docs/guides/app-deployment/application-deployment-guide.md
- content/en/docs/samples/bobs-books.md
- content/en/docs/samples/helidon-config/_index.md
- content/en/docs/samples/hello-helidon/_index.md
- content/en/docs/setup/install/installation.md
* Fix copy button code
* add copy buttons
* Fix indentation
> Rm/fix copy code (#827)

- content/en/docs/guides/ha/prod-upgrade.md
Minor fix (add a blank line) to make the copy button appear.
> fix copy button

- content/en/docs/monitoring/metrics/metrics.md
This PR adds instructions to the monitoring metrics page for Grafana dashboard discovery.
> Add Grafana dashboard discovery info

- config/_default/params.toml
- content/en/docs/samples/argo-cd.md
- content/en/docs/setup/cli/_index.md
- layouts/shortcodes/release_branch.html
Fixed release version, release branch and other text in CLI page, as appropriate.
> Fix release version and release branch, as appropriate

- content/en/docs/monitoring/metrics/metrics.md
Cherry-picked commit from release-1.5 branch, adds information about Grafana dashboard discovery.
> Add Grafana dashboard discovery info (#846)

- content/en/docs/troubleshooting/diagnostictools/analysisadvice/KeycloakDataMigrationFailure.md
If for some reason, the data load job fails and is unable to complete successfully on next retries, then the user can follow these steps to manually do the steps that the load job is supposed to do. The user will be shown link to this page in the vz analyze output if the job fails
> VZ-7337: Recover from terminal failure of data load job

- config/_default/params.toml
- content/en/docs/samples/argo-cd.md
- content/en/docs/setup/cli/_index.md
- layouts/shortcodes/release_branch.html
Fixed release version, release branch and other text in CLI page, as appropriate.
> Fix release version and release branch

- content/en/docs/samples/argo-cd.md
- content/en/docs/setup/install/multicluster-no-rancher.md
- content/en/docs/setup/install/multicluster.md
- content/en/docs/setup/install/profiles.md
Distinguish/clarify between installing and enabling components.
> clarify terms in text

- content/en/docs/troubleshooting/diagnostictools/analysisadvice/KeycloakDataMigrationFailure.md
> VZ-7337: Recover from terminal failure of data load job (#831)

- content/en/docs/troubleshooting/diagnostictools/analysisadvice/InsufficientCPU.md
* Insufficient CPU doc added under troubleshoot analysis advice
* Edits incorporated
---------
> VZ-8502  added insufficient cpu case into troubleshooting doc (#813)

- content/en/docs/samples/argo-cd.md
For right now, putting the Argo CD info in one place.
> Update Argo example

- content/en/docs/samples/argo-cd.md
* Update Argo example
* one typo fix
* rearrange bulleted items
* another tweak to the bulleted items
* incorporate edit from Deva
> Update Argo example (#880)

- content/en/docs/customize/opensearch.md
- content/en/docs/monitoring/logs/_index.md
This PR is to backport these changes from master to release-1.5 which enhances OpenSearch documentation.
https://github.com/verrazzano/docs/pull/874
https://github.com/verrazzano/docs/pull/878
> VZ 8763: Enhance OpenSearch related documentation.

- content/en/docs/troubleshooting/diagnostictools/analysisadvice/InsufficientCPU.md
* Insufficient CPU doc added under troubleshoot analysis advice
* Edits incorporated
---------
> VZ-8502 added insufficient cpu case into troubleshooting doc (#813)

- content/en/docs/setup/platforms/OCI/OCI.md
Backport NOTE from JIRA [VZ-8788](https://jira.oraclecorp.com/jira/browse/VZ-8788)
> Add NOTE (#887)

- content/en/docs/setup/platforms/kind/kind.md
Add x-ref to supported k8s versions
> Fix for VZ-3306 Documentation for kind should list the supported k8s versions for v8o

- content/en/docs/setup/platforms/kind/kind.md
Add x-ref to supported k8s versions.
> add x-ref to supported k8s (#895)

- content/en/docs/setup/platforms/kind/kind.md
* Update-doc-for-VZ-3286
* edits from Kevin
* minor edit
> Update-doc-for-VZ-3286 (#901)

- content/en/docs/setup/prereqs.md
- Added End of Error Correction info
- Moved the 'End of Error Correction' column ahead
- Added a footnote for the 'End of Error Correction' column
> Backport-VZ-8806: Updated End of Error Correction info #902

- content/en/docs/uninstall/backup/keycloak.md
Step 2: backup-secret.txt > backup-region.txt
> VZ-8887: File name fix

- content/en/docs/uninstall/backup/keycloak.md
Step 2: backup-secret.txt > backup-region.txt
> Backport of VZ-8887: File name fix #906

- content/en/docs/uninstall/backup/opensearch.md
Updated Indentation > Opensearch Backup recovery YAML
> Backport of VZ-8886 Updated Indentation > Opensearch Backup recovery YAML #907

- content/en/docs/applications/traits/ingress/ingress.md
- content/en/docs/quickstart/_index.md
- content/en/docs/setup/cli/_index.md
- content/en/docs/uninstall/upgrade/_index.md
As per [VZ-8786](https://jira.oraclecorp.com/jira/browse/VZ-8786) Include VZ Cli upgrade before running VZ upgrade - Pre-Reqs, added NOTE to CLI and upgrade docs
> upgrade cli VZ-8786

- content/en/docs/applications/traits/ingress/ingress.md
- content/en/docs/quickstart/_index.md
- content/en/docs/setup/cli/_index.md
- content/en/docs/uninstall/upgrade/_index.md
Backport as per [VZ-8786](https://jira.oraclecorp.com/jira/browse/VZ-8786) Include VZ Cli upgrade before running VZ upgrade - Pre-Reqs, added NOTE to CLI and upgrade docs.
> upgrade cli VZ-8786 (#919)

- config/_default/params.toml
> Switch to a foldable sidebar menu.

- content/en/docs/setup/prereqs.md
Backport to fix Alertmanager component spelling
> Fix component spelling (#931)

- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/prereqs.md
Doc updates for Release 1.4.4 Patch Release - Changes to master
> Doc updates for 1.4.4 Patch Release

- assets/scss/_variables_project.scss
- content/en/_index.html
- layouts/shortcodes/blocks/tile.html
This PR adds outlined tiles as shown below:
This PR is not intended to address other components of the home page
> VZ-8859 Adding tiles to vz homepage

- content/en/docs/customize/ingress.md
- content/en/docs/customize/ociLoadBalancerIPs.md
* Updating documentation for flexible LB shape
> VZ-7460 Updating documentation for flexible LB shape (#945)

- content/en/docs/setup/install/profiles.md
Documentation changes for new verrazzano installation profile: "none"
Summary of changes:
> Changes to profiles.md to include information about "none"
> VZ-8947: Doc changes for none profile

- content/en/docs/customize/installationOverrides.md
- content/en/docs/reference/API/vpo-verrazzano-v1alpha1.md
- content/en/docs/reference/API/vpo-verrazzano-v1beta1.md
Add a new page to document Installation Overrides
> vz-8849 documenting config map secret vz overrides

- content/en/docs/setup/install/profiles.md
Minor edits to the none profile description.
> tweak-none-profile-description

- content/en/docs/quickstart/_index.md
Moved CLI Setup link to the top of the section.
> Moved CLI Setup link

- content/en/docs/customize/installationOverrides.md
- content/en/docs/reference/API/vpo-verrazzano-v1alpha1.md
- content/en/docs/reference/API/vpo-verrazzano-v1beta1.md
Rewording, and adding values examples to Installation Overrides page
> vz-8849 follow up doc changes

- content/en/docs/backup/keycloak.md
A follow-up to the update made in PR https://github.com/verrazzano/docs/pull/958
> VZ-9161 - Keycloak - copy secret's password to the new cluster  

- content/en/docs/backup/keycloak.md
VZ-9161 - Copy secret's password to the new cluster
> VZ-9161 - Backport - Keycloak - copy secret's password to the new cluster (#975)

- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/prereqs.md
> VZ-8954: Uptaking Jaeger 1.42.0

- content/en/_index.html
I updated the text in the tiles, and I updated the one-line description of Verrazzano.
> updated tile text

- layouts/404.html
The home page link was reloading the same 404 page. So, modified to link (a direct link to https://verrazzano.io/latest/docs/).
> VZ: 9222 Updated link on 404 page

- content/en/docs/access/_index.md
This change includes the instruction to update the Keycloak admin password. Minor changes are included to the instruction to change Verrazzano user as well.
> Include the instruction to update the Keycloak admin password, release-1.5

- content/en/docs/access/_index.md
This change includes the instruction to update the Keycloak admin password. Minor changes are included to the instruction to change Verrazzano user as well.
> Include the instruction to update the Keycloak admin password, release-1.4

- content/en/docs/access/_index.md
- content/en/docs/customize/dns.md
- content/en/docs/samples/sock-shop.md
- content/en/docs/setup/install/cli-installation.md
- content/en/docs/setup/install/kubectl-installation.md
- content/en/docs/setup/private-registry/private-registry-full-distribution.md
- content/en/docs/setup/private-registry/private-registry.md
- content/en/docs/upgrade/upgrade.md
As per [VZ-9225](https://jira.oraclecorp.com/jira/browse/VZ-9225) Remove tabs in docs
> Remove tabs

- content/en/docs/access/_index.md
- content/en/docs/customize/dns.md
- content/en/docs/samples/sock-shop.md
- content/en/docs/setup/install/cli-installation.md
- content/en/docs/setup/install/kubectl-installation.md
- content/en/docs/setup/private-registry/private-registry-full-distribution.md
- content/en/docs/setup/private-registry/private-registry.md
- content/en/docs/upgrade/upgrade.md
* Remove tabs
* some fixes, not all
* Fixes - to sock-shop and upgrade topics
* Fix instruction steps
* minor formatting fixes
* Clarification from PBhat
---------
> Remove tabs (#993)

- 404.html
The home page link was reloading the same 404 page. So, modified the link - a direct link to https://verrazzano.io/
> VZ: 9222 Updated the home page link on 404 page

- go.mod
- go.sum
Ran hugo mod tidy
Confirmed that local doc rendering works
> Cleanup modules with hugo mod tidy

- content/en/docs/quickstart/_index.md
- content/en/docs/setup/install/mc-install/advanced/register-kubectl.md
> minor edits and correction

- content/en/docs/quickstart/_index.md
- content/en/docs/setup/install/mc-install/advanced/register-kubectl.md
* minor edits and correction
* fix numbering and indentation
> minor edits and correction (#1014)

- content/en/docs/quickstart/_index.md
> fix number x-refs in doc

- content/en/docs/observability/logs/tracing/jaeger-tracing.md
Separate copy button code versus sample output.
> remove output from copied code

- content/en/docs/samples/helidon-config/_index.md
- content/en/docs/samples/hello-helidon/_index.md
- content/en/docs/samples/multicluster/sock-shop/_index.md
- content/en/docs/samples/multicluster/todo-list/_index.md
- content/en/docs/samples/sock-shop.md
- content/en/docs/samples/spring-boot.md
- content/en/docs/setup/install/modify-installation.md
* fix copy button
To exclude comments
* Formatting fix
* Update single cluster sock shop example
---------
> fix copy button (#1029)

- content/en/docs/observability/logs/tracing/jaeger-tracing.md
Basically, cleaned up the doc a bit and re-arranged some sections for a more logical presentation. This doc will be re-written and expanded for the 1.6 release. However, if there are any sections in which you want to add content, have comments, or perhaps, want to complete the example in the Manage Jaeger indices in OpenSearch section, please give me that information and I will incorporate it. Thank you.
> Update current Jaeger doc

- content/en/docs/observability/monitoring/metrics/configure/thanos/thanos.md
- One Technical fix (command)
- Rest are literary fixes
> Thanos topic update - Minor fixes (Ali's comments)

- content/en/docs/troubleshooting/troubleshooting-fluentd.md
Add troubleshooting guide for fluentd due to permission to read/write.
> VZ-9434: Add troubleshooting guide for fluentd

- content/en/docs/troubleshooting/troubleshooting-fluentd.md
* backport troubleshooting guide for fluentd  to release 1.5
> VZ-9434: Backport Add troubleshooting guide for fluentd (#1041)

- content/en/docs/customize/grafana.md
- content/en/docs/reference/API/vco-clusters-v1alpha1.md
- content/en/docs/reference/API/vpo-verrazzano-v1alpha1.md
- content/en/docs/reference/API/vpo-verrazzano-v1beta1.md
Docs for changes done in https://github.com/verrazzano/verrazzano/pull/5844 to support SMTP configuration in Grafana
> VZ-9204: Docs for SMTP configuration in Verrazzano

- content/en/docs/backup/keycloak.md
This change updates the backup and restore instructions for Keycloak.
> VZ-8888: Update Keycloak backup and restore instructions

- content/en/docs/setup/private-registry/private-registry-full-distribution.md
- content/en/docs/setup/private-registry/private-registry.md
Backport of https://github.com/verrazzano/docs/pull/1047 to release-1.5.
> VZ-9545: Updates to the private registry installation instructions (release-1.5)

- content/en/docs/applications/workloads/coherence/coherence.md
- content/en/docs/applications/workloads/helidon/helidon.md
- content/en/docs/applications/workloads/weblogic/_index.md
- content/en/docs/backup/keycloak.md
- content/en/docs/customize/certificates.md
- content/en/docs/customize/opensearch.md
- content/en/docs/customize/storage.md
- content/en/docs/guides/lift-and-shift/lift-and-shift.md
- content/en/docs/networking/security/net-security.md
- content/en/docs/samples/bobs-books.md
- content/en/docs/samples/todo-list.md
- content/en/docs/security/appsec/appsec.md
- content/en/docs/security/rbac/rbac.md
- content/en/docs/setup/cli/_index.md
- content/en/docs/setup/install/cli-installation.md
- content/en/docs/setup/install/kubectl-installation.md
- content/en/docs/setup/install/profiles.md
- content/en/docs/setup/platforms/Generic/generic.md
- content/en/docs/setup/platforms/OCI/OCI.md
- content/en/docs/setup/platforms/kind/kind.md
- content/en/docs/setup/prereqs.md
- content/en/docs/troubleshooting/troubleshooting-fluentd.md
- content/en/docs/upgrade/upgrade.md
Currently, NOTES appear yellow. I changed informational NOTES to appear blue and Warning NOTES to appear red
> Changed the color of NOTES

- content/en/docs/setup/private-registry/private-registry-full-distribution.md
- content/en/docs/setup/private-registry/private-registry.md
This reverts commit 3cde1272c2e462251fe878acb00705e1fcf24e84.
> VZ-9545: Revert private registry doc updates

- content/en/docs/quickstart/_index.md
- content/en/docs/releasenotes/_index.md
- As per the new ToC structure, moved RNs section to top of the Nav.
- As decided by the doc team, there are no sub-topics for this update (for now). They will added in the subsequent releases.
> ToC Implementation - Release Notes

- content/en/docs/quickstart/_index.md
- content/en/docs/releasenotes/_index.md
- Backport to 1.5 
- As per the new ToC structure, moved RNs section to top of the Nav.
- As decided by the doc team, there are no sub-topics for this update (for now). They will added in the subsequent releases.
> Backport - ToC Implementation - Release Notes #1052

- content/en/docs/setup/install/profiles.md
As per @david-cabelus-oracle in [VZ-9663](https://jira.oraclecorp.com/jira/browse/VZ-9663), removed the none profile from the docs.
> remove none profile column

- content/en/docs/setup/prereqs.md
> VG backport prereq

- content/en/docs/about/VerrazzanoMultiCluster.md
- content/en/docs/about/VerrazzanoOAM.md
- content/en/docs/about/VerrazzanoProject.md
- content/en/docs/about/_index.md
- content/en/docs/about/features.md
Add alias definitions for About sections files that were moved from Concepts
> add aliases

- content/en/docs/about/VerrazzanoMultiCluster.md
- content/en/docs/about/VerrazzanoOAM.md
- content/en/docs/about/VerrazzanoProject.md
- content/en/docs/about/_index.md
- content/en/docs/about/features.md
Backport concept section alias definitions
> add aliases (#1081)

- content/en/docs/setup/prereqs.md
> VZ-9674: Documentation: compute requirements don't match the requirements validator webhook

- content/en/docs/customize/fluentd.md
- content/en/docs/customize/nfs.md
- content/en/docs/troubleshooting/troubleshooting-fluentd.md
updated required permissions by fluentd in troublehsooting guide
> VZ-9653: Update required permissions by fluentd in troublehsooting guide

- config/_default/params.toml
- content/en/docs/observability/tracing/application-tracing.md
Updated Jaeger short codes for 1.42. Updated links.
> Updated Jaeger short codes for 1.42. Updated links.

- content/en/docs/observability/tracing/configure-tracing.md
Incorporate feedback from  [sherwoodzern](https://github.com/sherwoodzern).
> edit note text

- content/en/docs/setup/access/_index.md
- content/en/docs/setup/access/password.md
- content/en/docs/setup/install/perform/cli-installation.md
- content/en/docs/setup/install/perform/kubectl-installation.md
- content/en/docs/setup/install/perform/profiles.md
- content/en/docs/setup/install/prepare/cli-setup.md
- content/en/docs/setup/install/prepare/platforms/Generic/generic.md
- content/en/docs/setup/install/prepare/platforms/OCI/OCI.md
- content/en/docs/setup/install/prepare/platforms/OLCNE/OLCNE.md
- content/en/docs/setup/install/prepare/platforms/_index.md
- content/en/docs/setup/install/prepare/platforms/kind/kind.md
- content/en/docs/setup/install/prepare/platforms/minikube/minikube.md
- content/en/docs/setup/install/prepare/prereqs.md
- content/en/docs/setup/mc-install/_index.md
- content/en/docs/setup/mc-install/advanced/multicluster-no-rancher.md
- content/en/docs/setup/mc-install/advanced/syncclusters.md
- content/en/docs/setup/mc-install/deregister-install.md
- content/en/docs/setup/mc-install/multicluster.md
- content/en/docs/setup/mc-install/register/register-kubectl.md
- content/en/docs/setup/mc-install/troubleshooting-multicluster.md
- content/en/docs/setup/mc-install/verify-install.md
- content/en/docs/setup/modify-installation.md
- content/en/docs/setup/quickstart/_index.md
- content/en/docs/setup/uninstall/_index.md
- content/en/docs/setup/uninstall/uninstall.md
- content/en/docs/setup/uninstall/uninstall_considerations.md
- content/en/docs/setup/upgrade/_index.md
- content/en/docs/setup/upgrade/perform.md
- content/en/docs/setup/upgrade/upgrade-mc.md
- content/en/docs/setup/upgrade/verify.md
* add aliases
* add more aliases
* one more
* remove aliases from split out docs
* few more unnecessary aliases
> Rm/add acess aliases (#1116)

- content/en/docs/applications/kubernetes/_index.md
- content/en/docs/applications/kubernetes/auth_policy.md
- content/en/docs/applications/kubernetes/certificate.md
- content/en/docs/applications/kubernetes/create_kubernetes.md
- content/en/docs/applications/kubernetes/gateway_virtual_service.md
- content/en/docs/applications/kubernetes/wiring-metrics.md
- This is a new section: Kubernetes Application Deployment. We worked with Bryan Tidd to create this section. 
- This is added at the end of the Applications chapter. 
- After this PR is complete, we will update the Applications chapter flow to match the new ToC.
> VZ-9427: Kubernetes Application Deployment

- content/en/docs/applications/kubernetes/wiring-metrics.md
Link update - after a conflict in merges
> Link update

- content/en/docs/setup/private-registry/private-registry-full-distribution.md
- content/en/docs/setup/private-registry/private-registry.md
Renamed topic title as per ToC reorg - 'Use a private registry' to 'Install in a Disconnected Environment'
> Update to setup section

- content/en/docs/setup/install/perform/cli-installation.md
- content/en/docs/setup/install/perform/kubectl-installation.md
- content/en/docs/setup/quickstart/_index.md
- content/en/docs/troubleshooting/FAQ.md
- content/en/docs/troubleshooting/_index.md
- content/en/docs/troubleshooting/diagnostictools/VZBugReportCLI.md
- content/en/docs/troubleshooting/diagnostictools/VerrazzanoAnalysisTool.md
- content/en/docs/troubleshooting/diagnostictools/analysisadvice/_index.md
ToC implementation - Troubleshoot and FAQ chapter - as per the Reorg wiki
Fluentd and MySQL are existing topics (not yet considered as per the Reorg wiki)
> Backport - ToC implementation - Troubleshoot and FAQ (#1137)

- content/en/docs/setup/private-registry/private-registry-full-distribution.md
- content/en/docs/setup/private-registry/private-registry.md
Last item on docs-reorg (for now)
> edit private registry title

- content/en/docs/observability/logging/configure-opensearch/opensearch.md
- content/en/docs/observability/logging/configure-opensearch/storage.md
- content/en/docs/observability/logging/fluentd/fluentd.md
- content/en/docs/observability/monitoring/configure/grafana/grafana.md
Add alias definitions for docs moved into Observability section from Customize
> Observability aliases

- content/en/docs/observability/logging/logs.md
- content/en/docs/observability/logging/search.md
- content/en/docs/observability/monitoring/configure-metrics.md
- content/en/docs/observability/tracing/configure-tracing.md
- content/en/docs/observability/tracing/view-traces.md
There can be only one alias for the files in the doc set. I removed any duplicates.
> remove duplicate aliases

- content/en/docs/setup/private-registry/private-registry-full-distribution.md
- content/en/docs/setup/private-registry/private-registry.md
Backport of renaming Use a Private Registry docs to Install Verrazzano in a Disconnected Environment
> edit private registry title (#1150)

- content/en/docs/applications/_index.md
- content/en/docs/applications/kubernetes/create_kubernetes.md
- content/en/docs/observability/logging/_index.md
- content/en/docs/observability/logging/troubleshoot.md
- content/en/docs/setup/access/console-credentials.md
- content/en/docs/setup/access/console-urls.md
- content/en/docs/setup/install/prepare/platforms/OLCNE/_index.md
- content/en/docs/setup/uninstall/uninstall.md
- content/en/docs/troubleshooting/troubleshooting-fluentd.md
- content/en/docs/troubleshooting/troubleshooting-mysql.md
Updated as per latest feedback on the ToC reorg
> ToC feedback updates

- content/en/docs/applications/_index.md
- content/en/docs/applications/kubernetes/create_kubernetes.md
- content/en/docs/observability/logging/_index.md
- content/en/docs/observability/logging/troubleshoot.md
- content/en/docs/setup/access/console-credentials.md
- content/en/docs/setup/access/console-urls.md
- content/en/docs/setup/install/prepare/platforms/OLCNE/_index.md
- content/en/docs/setup/uninstall/uninstall.md
- content/en/docs/troubleshooting/troubleshooting-fluentd.md
- content/en/docs/troubleshooting/troubleshooting-mysql.md
> Backport ToC feedback updates (#1162)

- content/en/docs/applications/delivery/_index.md
- content/en/docs/applications/delivery/deploy.md
- content/en/docs/applications/delivery/enable.md
- content/en/docs/applications/oam/deploy-app.md
- content/en/docs/applications/oam/workloads/coherence/coherence.md
- content/en/docs/applications/oam/workloads/helidon/helidon.md
- content/en/docs/applications/oam/workloads/weblogic/_index.md
- content/en/docs/applications/troubleshooting-application-deployment.md
- content/en/docs/troubleshooting/FAQ.md
Troubleshooting, guides, applications
> add aliases (#1166)

- content/en/docs/reference/vpo-verrazzano-v1alpha1.md
- content/en/docs/reference/vpo-verrazzano-v1beta1.md
This pull request includes regenerated API docs.  Included are fixes for broken links and additions for the FluentbitOpensearchOutput and the FluentOperator components.
> VZ-9880: update generated API doc

- content/en/docs/observability/logging/fluent-operator.md
Documentation for the new component fluent-operator.
> VZ-9049: Documentation for Fluent-Operator

- content/en/docs/observability/logging/configure-opensearch/opensearch.md
* update Pre-built plug-ins for OpenSearch
> back port PR to update Pre-built plug-ins for OpenSearch

- content/en/docs/setup/mc-install/verify-install.md
Includes rancherRegistration in the documentation, to validate the managed cluster registration.
> Update sample output of managed cluster registration to include rancherRegistration

- content/en/docs/setup/install/prepare/prereqs.md
As per VZ-10039, added the required two load balancers to the prereqs
> Add load balancers to prereqs

- content/en/docs/setup/install/prepare/prereqs.md
* add LBs to prereqs
* minor edit
* another minor edit
> Add load balancers to prereqs (#1187)

- content/en/docs/introduction/features.md
Fixed a link in the Introduction section.
> Link update - moved section

- content/en/docs/introduction/features.md
Fixed a link in the Introduction section.
> Backport Link update - moved section #1195

- content/en/docs/releasenotes/_index.md
The 1.6 Release Notes are still a work in progress. Feel free to provide input or comments.
> updates to RNs

- content/en/docs/reference/vpo-verrazzano-v1alpha1.md
- content/en/docs/reference/vpo-verrazzano-v1beta1.md
Update generated API docs to include clusterAPI updates
> Update API docs to include clusterAPI updates

- content/en/docs/reference/vao-clusters-v1alpha1.md
This pull request fixes a broken network policies link in the generated API docs.
> Fix network policies link

- content/en/docs/setup/private-registry/private-registry.md
* Add note on resolving host names
* Add to host names and dns to add context
> Backport - Add note on resolving host names (#1181)

- config/_default/config.toml
> Update the drop-down version menu

- config/_default/config.toml
> update version menu

- content/en/docs/observability/monitoring/configure/prometheus.md
- content/en/docs/observability/monitoring/troubleshooting-prometheus.md
Backport Prometheus storage updates to release-1.6. See #1229 for details.
> VZ-10071: Add Prometheus storage information and troubleshooting (#1229)

- content/en/docs/troubleshooting/diagnostictools/analysisadvice/KontainerDriverNotReady.md
> VZ-10276: add analyze of KontainerDriver resources

- content/en/docs/observability/logging/oci-logging.md
To avoid confusion, updated the title from "Install Verrazzano" to "Specify custom logs".
> Update to fix VZ-9516

- content/en/docs/setup/install/perform/kubectl-installation.md
> VZ-10074: Verrazzano installation on AKS Cluster

- content/en/docs/setup/install/perform/kubectl-installation.md
> Backport - VZ-10074: Verrazzano installation on AKS Cluster #1240

- content/en/docs/setup/private-registry/private-registry-full-distribution.md
- content/en/docs/setup/private-registry/private-registry.md
As per Mike's feedback:
1 - Moved the Note after the first paragraph
2 - Added the alert Note tag
> Fixed feedback comment

- content/en/docs/setup/private-registry/private-registry-full-distribution.md
- content/en/docs/setup/private-registry/private-registry.md
As per Mike's feedback:
1 - Moved the Note after the first paragraph
2 - Added the alert Note tag
> Fixed feedback comment #1241

- content/en/docs/observability/logging/oci-logging.md
To avoid confusion, updated the title from "Install Verrazzano" to "Specify custom logs".
> Backport - Update to fix VZ-9516 #1242

- content/en/docs/troubleshooting/diagnostictools/analysisadvice/RancherClusterNotReady.md
Cherry pick changes from master
> VZ-10280: Add diagnostic section for Rancher cluster not being ready

- content/en/docs/troubleshooting/diagnostictools/analysisadvice/ClusterApiClusterNotReady.md
- content/en/docs/troubleshooting/diagnostictools/analysisadvice/KontainerDriverNotReady.md
> VZ-10278: add vz analyze runbook for cluster API resource not ready (#1256)

- config/_default/config.toml
- content/en/docs/_index.md
- content/en/docs/setup/install/prepare/prereqs.md
* remove-x-refs-to-archive-page
* Remove Release History info
* add back links
> remove-x-refs-to-archive-page-VZ-9735 (#1239)

- content/en/docs/setup/install/prepare/platforms/kind/kind.md
> update-k8s-version (#1265)

- content/en/docs/setup/upgrade/prepare.md
(cherry picked from commit 85fa79ac91ffe6a98a03800cc4ff2571a0e6b217)
> VZ-10297 WebLogic domain restart correction backport

- content/en/docs/releasenotes/_index.md
> Release 1.5.4 notes (#1275)

- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/provision-cluster/ocne-oci.md
* Add VCN quick create and other ui changes
* Literary and organizational edits
* minor wording edit
> Backport to 1.6 - Add VCN quick create and other ui changes (#1280)

- content/en/docs/applications/oam/workloads/weblogic/_index.md
* First pass updates
* Update deploying app section for VZ-8782
* restore original x-ref
* Add sample workload component
* Minor edit
* add x-ref to spec
* update x-ref
> Update WebLogic Workload documentation for VZ-8782 (#1273)

- content/en/docs/setup/install/prepare/platforms/OLCNE/vcn.md
- content/en/docs/setup/provision-cluster/ocne-oci.md
- content/en/docs/troubleshooting/troubleshooting-clusterapi.md
* Adds troubleshooting info for clusterapi
* Fix typo
* Literary edits
* Make specific to OCNE
* various edits
* Describes VCN minimum specs
* Add link to vcn req page + minor edit
> Backport to 1.6 OCNE cluster creation troubleshooting (#1269)

- content/en/docs/releasenotes/_index.md
> Release notes for 1.6.2 draft

- config/_default/params.toml
- content/en/docs/releasenotes/_index.md
> 1.6.2 Doc Notes

- content/en/docs/_index.md
Make changes for 1.6.2 To Archive
> Make changes for 1.6.2 To Archive

- content/en/docs/setup/private-registry/private-registry.md
Fixed jq commands - "jq command cannot be split into multiple lines, because the whole thing is single-quoted."
> Fixed jq commands

- content/en/docs/guides/ha/ha.md
- content/en/docs/networking/istio.md
- content/en/docs/networking/security/certificates.md
- content/en/docs/networking/traffic/dns.md
- content/en/docs/networking/traffic/externalLBs.md
- content/en/docs/networking/traffic/ingress.md
- content/en/docs/networking/traffic/ociLoadBalancerIPs.md
- content/en/docs/observability/logging/configure-opensearch/opensearch.md
- content/en/docs/observability/logging/configure-opensearch/storage.md
- content/en/docs/observability/logging/fluentd/fluentd.md
- content/en/docs/observability/monitoring/configure/grafana/grafana.md
- content/en/docs/observability/monitoring/configure/prometheus.md
- content/en/docs/security/appsec/appsec.md
- content/en/docs/security/keycloak/keycloak.md
- content/en/docs/security/proxies/authproxy.md
Update alias definitions with the latest locations for the Customize topics, as per [VZ-10423](https://jira.oraclecorp.com/jira/browse/VZ-10423) WebLogic for OKE Marketplace Doc Links Broken
> update alias definitions

- content/en/docs/guides/ha/ha.md
- content/en/docs/networking/istio.md
- content/en/docs/networking/security/certificates.md
- content/en/docs/networking/traffic/dns.md
- content/en/docs/networking/traffic/externalLBs.md
- content/en/docs/networking/traffic/ingress.md
- content/en/docs/networking/traffic/ociLoadBalancerIPs.md
- content/en/docs/observability/logging/configure-opensearch/opensearch.md
- content/en/docs/observability/logging/configure-opensearch/storage.md
- content/en/docs/observability/logging/fluentd/fluentd.md
- content/en/docs/observability/monitoring/configure/grafana/grafana.md
- content/en/docs/observability/monitoring/configure/prometheus.md
- content/en/docs/security/appsec/appsec.md
- content/en/docs/security/keycloak/keycloak.md
- content/en/docs/security/proxies/authproxy.md
* update alias definitions
* add aliases for 1.3 URLs
* update k8s URL with shortcode
> update alias definitions (#1307)

- content/en/docs/networking/traffic/externalLBs.md
- content/en/docs/observability/logging/configure-opensearch/storage.md
- content/en/docs/security/appsec/appsec.md
Update docs to use k8s API short code
> use k8s short code

- content/en/docs/guides/ha/ha.md
- content/en/docs/networking/istio.md
- content/en/docs/networking/security/certificates.md
- content/en/docs/networking/traffic/dns.md
- content/en/docs/networking/traffic/externalLBs.md
- content/en/docs/networking/traffic/ingress.md
- content/en/docs/networking/traffic/ociLoadBalancerIPs.md
- content/en/docs/observability/logging/configure-opensearch/opensearch.md
- content/en/docs/observability/logging/configure-opensearch/storage.md
- content/en/docs/observability/logging/fluentd/fluentd.md
- content/en/docs/observability/monitoring/configure/grafana/grafana.md
- content/en/docs/observability/monitoring/configure/prometheus.md
- content/en/docs/security/keycloak/keycloak.md
- content/en/docs/security/proxies/authproxy.md
- content/en/docs/setup/upgrade/perform.md
* remove 1.6 URLs from aliases
* remove upgrade\upgrade alias
> remove 1.6 URLs from aliases (#1318)

- content/en/docs/releasenotes/_index.md
Adding release notes for 1.4.6
> Add release notes for 1.4.6

- config/_default/params.toml
- content/en/docs/releasenotes/_index.md
> 1.4.6 Release Notes Backport

- content/en/docs/observability/monitoring/configure/prometheus.md
- content/en/docs/observability/storage.md
- content/en/docs/security/keycloak/keycloak.md
Backport change to move the Customize Persistent Storage doc.
> Move Customize Persistent Storage doc

- content/en/docs/troubleshooting/troubleshooting-clusterapi.md
> update kubectl commands to get capi log files (#1328)

- content/en/docs/setup/install/prepare/platforms/OLCNE/vcn.md
- content/en/docs/troubleshooting/troubleshooting-clusterapi.md
* Add example security rules for OCI VCNs
* Minor wording edits
* Fix plurals
> Backport to 1.6 - VCN example tables

- content/en/docs/setup/private-registry/private-registry.md
- Added Prerequisites as required
- The install VZ topic exits
> VZ-9974 (Part-2)

- content/en/docs/releasenotes/_index.md
Initial draft of 1.5.5 release notes
> Initial draft of 1.5.5 release notes

- content/en/docs/setup/private-registry/private-registry.md
- Added Prerequisites as required
- The install VZ topic exits
> Backport - 1.6 - VZ-9974 (Part-2) (#1317)

- content/en/docs/setup/private-registry/private-registry.md
- Backport PR
- Added Prerequisites as required
- The install VZ topic exits
> Backport - 1.5 - VZ-9974 (Part-2) (#1317)

- content/en/docs/releasenotes/_index.md
> Updated 1.5 release notes

- config/_default/params.toml
> Update params.toml file

- content/en/docs/_index.md
- content/en/docs/applications/_index.md
- content/en/docs/backup/_index.md
- content/en/docs/help/_index.md
- content/en/docs/setup/_index.md
- content/en/docs/support/_index.md
- As per JIRA VZ-10505: Added Support/Help page
- Fixed comments
> VZ-10505: Added Support/Help page

- content/en/docs/_index.md
- content/en/docs/applications/_index.md
- content/en/docs/backup/_index.md
- content/en/docs/help/_index.md
- content/en/docs/setup/_index.md
> Backport 1.6 - VZ-10505: Added Support/Help page (#1352)

- content/en/docs/_index.md
- content/en/docs/applications/_index.md
- content/en/docs/backup/_index.md
- content/en/docs/help/_index.md
- content/en/docs/setup/_index.md
> Backport 1.5 - VZ-10505: Added Support/Help page (#1352)

- content/en/docs/_index.md
- content/en/docs/help/_index.md
> Backport 1.4 - VZ-10505: Added Support/Help page (#1352)

- config/_default/config.toml
> Remove link to Release History

- config/_default/config.toml
> Remove link to Release History (#1357)

- content/en/docs/_index.md
- content/en/docs/help/_index.md
- Backport to 1.3 release. 
- Updated as per VZ-10505.
> Backport 1.3 - VZ-10505: Added Support/Help page (#1352)

- content/en/docs/observability/monitoring/configure/thanos.md
- content/en/docs/observability/tracing/configure-tracing.md
> Minor edits (#1356)

- content/en/docs/support/_index.md
Updated Release History for 1.6.4
> Updated Release History for 1.6.4

- content/en/docs/security/keycloak/keycloak.md
Back port changes from master branch
> VZ-10285: Add help for customizing MySQL my.cnf settings (#1379)

- content/en/docs/releasenotes/_index.md
Fixed Release Notes for when WME version was upgraded
> Fix Release Notes

- content/en/docs/observability/logging/configure-opensearch/opensearch.md
- content/en/docs/observability/monitoring/troubleshooting-prometheus.md
- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/install/prepare/platforms/Generic/generic.md
- content/en/docs/setup/install/prepare/platforms/OLCNE/vcn.md
- content/en/docs/setup/install/prepare/platforms/kind/kind.md
- content/en/docs/setup/mc-install/advanced-mc-install.md
- content/en/docs/setup/private-registry/private-registry.md
According to the latest Oracle Style Guide, internet is now lowercase.
> Updates for style guide

- content/en/docs/observability/monitoring/configure/alertmanager.md
Update Alertmanager doc as per suggested.
> Update alertmanager info

- content/en/docs/releasenotes/_index.md
> Make changes to 1.6.5 release notes based on feedback

- content/en/docs/releasenotes/_index.md
* Make changes to 1.6.5 release notes based on feedback
> Make changes to 1.6.5 release notes based on feedback (#1416)

- config/_default/params.toml
- content/en/docs/releasenotes/_index.md
Initial pass of 1.5.6 release notes
> 1.5.6 Release Notes

- content/en/docs/_index.md
- content/en/docs/support/_index.md
Backport of RH table changes to 1.4 docs.
> Update link to RH table (#1438)

- content/en/docs/applications/oam/workloads/weblogic/_index.md
I made updates to the Deploy WebLogic applications in Verrazzano section to include DoPV specification and configuration.
> Add DoPV info

- content/en/docs/applications/oam/workloads/weblogic/_index.md
* Add DoPV info
* minor edit
* more edits
> Add DoPV info (#1455)

- content/en/docs/setup/install/prepare/platforms/Generic/generic.md
- content/en/docs/setup/install/prepare/platforms/OCI/OCI.md
Backport clarify OKE requirements.
> Clarify OKE requirements (#1453)

- content/en/docs/setup/install/prepare/platforms/kind/kind.md
* Update kind cluster instructions
* Update as per Davis suggestion
> Update kind cluster instructions (#1463)

- content/en/docs/reference/vao-clusters-v1alpha1.md
- content/en/docs/reference/vao-oam-v1alpha1.md
- content/en/docs/reference/vco-clusters-v1alpha1.md
- content/en/docs/reference/vpo-verrazzano-v1alpha1.md
- content/en/docs/reference/vpo-verrazzano-v1beta1.md
> VZ-11099 regenerate the API docs with formatting changes

- content/en/docs/reference/API/Multicluster/MultiClusterSecret.md
Substitute example password and user name with placeholders.
> Substitute-password-username

- content/en/docs/backup/argocd.md
- content/en/docs/backup/keycloak.md
- content/en/docs/backup/opensearch.md
- content/en/docs/backup/rancher.md
- content/en/docs/setup/upgrade/perform.md
Add note with recommendations for upgrading to VZ v1.7 or later.
> Add Upgrade Note for v1.7+

- content/en/docs/releasenotes/_index.md
- content/en/docs/support/_index.md
Initial pass of 1.6.8 release notes on master
> Initial pass of 1.6.8 release notes on master

- content/en/docs/observability/logging/configure-opensearch/opensearch.md
Add info about node topology modification for opster opensearch after verrazzano is installed or upgraded
> Add info about node topology modification for opster opensearch

- content/en/docs/setup/provision-cluster/managed-cluster-vz.md
* Cluster api add-on, vz fleet
* Remove 'remote', other edits
* Fixing literary edits
* Change single step task to bullet point
* Bullet to sentence
> Cluster api add-on (#1498)

- content/en/docs/_index.md
> update Release History table

- content/en/docs/setup/install/prepare/prereqs.md
Add VZ 1.7 support for Kubernetes to the prereqs.
> Update Kubernetes support info

- content/en/docs/setup/install/prepare/prereqs.md
> Update Kubernetes support info (#1527)

- content/en/docs/reference/vco-clusters-v1alpha1.md
- content/en/docs/reference/vpo-verrazzano-v1alpha1.md
- content/en/docs/reference/vpo-verrazzano-v1beta1.md
Update API reference doc in master.
> Update API reference doc in master

- content/en/docs/_index.md
Update support info info on the archive branch
> Update RH support info

- content/en/docs/advanced/_index.md
- content/en/docs/advanced/ocne-azure.md
- content/en/docs/advanced/ocne-vsphere.md
- content/en/docs/releasenotes/_index.md
- content/en/docs/setup/provision-cluster/CAPI.md
- content/en/docs/troubleshooting/_index.md
* OCNE on Azure via CAPI
* now with vSphere + other updates
* Reorder ISO and deploy vm steps
* minor edits
> OCNE on Azure or vSphere (#1535)

- content/en/docs/releasenotes/_index.md
Initial draft of RN Notes on Master for 1.6.10
> Initial draft of RN Notes on Master for 1.6.10

- content/en/docs/releasenotes/_index.md
- content/en/docs/support/_index.md
Add release notes for 1.6.10 to the 1.7 branch
> Add release notes for 1.6.10 to the 1.7 branch

- config/_default/params.toml
- content/en/docs/releasenotes/_index.md
Add 1.6.10 release notes changes to the 1.6 branch
> Add 1.6.10 release notes changes to the 1.6 branch

- content/en/docs/support/_index.md
Edit release table for 1.6.10 release on master
> Edit release table for 1.6.10 release on master

- content/en/docs/_index.md
Add release table changes to the 1.6.10 release to the archive branch
> Add release table changes to the 1.6.10 release to the archive branch

- content/en/docs/observability/logging/fluent-operator.md
Backport of #1554 to release-1.7.
> Fix typo in Fluent Bit commands (release-1.7)

- content/en/docs/observability/logging/fluent-operator.md
Backport of #1554 to release-1.6.
> Fix typo in Fluent Bit commands (release-1.6)

- content/en/docs/setup/install/prepare/platforms/OLCNE/_index.md
- content/en/docs/setup/install/prepare/platforms/OLCNE/nfs.md
- content/en/docs/setup/upgrade/kubernetes-upgrade.md
* Update links to OCNE docs to OCNE 1.7
* Changed to more specific link
> Update links to OCNE docs to OCNE 1.7 (#1557)

- content/en/docs/guides/migrate/wko.md
This is a first pass at the Cert-Manager Migration Guide.
> First pass at WKO migration doc

- content/en/docs/guides/migrate/_index.md
- content/en/docs/guides/migrate/install/_index.md
- content/en/docs/guides/migrate/install/cert-manager/_index.md
- content/en/docs/guides/migrate/install/fluent/_index.md
- content/en/docs/guides/migrate/install/istio/_index.md
- content/en/docs/guides/migrate/install/nginx/_index.md
- content/en/docs/guides/migrate/install/opensearch/_index.md
- content/en/docs/guides/migrate/install/prometheus/_index.md
- content/en/docs/guides/migrate/install/weblogic/_index.md
- content/en/docs/guides/migrate/integrate/_index.md
- content/en/docs/guides/migrate/integrate/cert-manager/_index.md
- content/en/docs/guides/migrate/integrate/fluent/_index.md
- content/en/docs/guides/migrate/integrate/istio/_index.md
- content/en/docs/guides/migrate/integrate/nginx/_index.md
- content/en/docs/guides/migrate/integrate/opensearch/_index.md
- content/en/docs/guides/migrate/integrate/prometheus/_index.md
- content/en/docs/guides/migrate/integrate/weblogic/_index.md
Add new migration doc structure.  This will be used to fill in details in subsequent PRs.
> Add new migration doc structure

- content/en/docs/end_support/_index.md
- content/en/docs/guides/migrate/_index.md
- content/en/docs/releasenotes/_index.md
- content/en/docs/support/_index.md
Added NOTE to the TOC and relevant places in the documentation to announce the End of Premier Support for Verrazzano.
> End of Premier Support note

- content/en/docs/guides/migrate/_index.md
Added back the VZ to OCNE migration guides.
> Add migration guides back

- content/en/docs/_index.md
- content/en/docs/advanced/_index.md
- content/en/docs/applications/_index.md
- content/en/docs/backup/_index.md
- content/en/docs/examples/_index.md
- content/en/docs/guides/_index.md
- content/en/docs/introduction/_index.md
- content/en/docs/networking/_index.md
- content/en/docs/observability/_index.md
- content/en/docs/reference/_index.md
- content/en/docs/security/_index.md
- content/en/docs/setup/_index.md
- content/en/docs/troubleshooting/_index.md
And, to the documentation landing page.
> Add End of Premier Support Note to every index page

- content/en/docs/_index.md
- content/en/docs/advanced/_index.md
- content/en/docs/applications/_index.md
- content/en/docs/backup/_index.md
- content/en/docs/end_support/_index.md
- content/en/docs/examples/_index.md
- content/en/docs/guides/_index.md
- content/en/docs/introduction/_index.md
- content/en/docs/networking/_index.md
- content/en/docs/observability/_index.md
- content/en/docs/reference/_index.md
- content/en/docs/releasenotes/_index.md
- content/en/docs/security/_index.md
- content/en/docs/setup/_index.md
- content/en/docs/support/_index.md
- content/en/docs/troubleshooting/_index.md
* End of Premier Support note
* Hide migration guides
> End of Premier Support note (#1568)

- content/en/docs/guides/migrate/integrate/istio/_index.md
Fills in the "Network Policies" section of the integrate/Istio migration doc.
> VZ-11751: Migration - Document Istio Network Policies

- content/en/docs/guides/migrate/integrate/prometheus/_index.md
This PR adds the sample instruction to create an ingress to Prometheus
> VZ-11750: Ingress integration with Prometheus

- content/en/docs/guides/migrate/install/opensearch/_index.md
PR includes:
- updated guide to migrate OpenSearch on OCNE under guide section.
> VZ-11755: update guide to migrate OpenSearch on OCNE

- content/en/docs/guides/migrate/_index.md
> Add Background information to Migration Guides section

- content/en/docs/guides/migrate/install/opensearch/_index.md
- content/en/docs/guides/migrate/integrate/opensearch/_index.md
The PR adds the integration guide for OpenSearch that explains how to integrate OpenSearch with other component like fluentbit, Promtheus etc.
> VZ: 11755  update integration guide for OpenSearch

- content/en/docs/guides/migrate/install/prometheus/_index.md
Changed some heading levels, otherwise there were only one or two minor text edits.
> Doc Review

- content/en/docs/guides/migrate/install/istio/_index.md
> Review install Istio doc

- content/en/docs/guides/migrate/install/oauth2-proxy/_index.md
> Install OAuth2 Proxy doc review

- content/en/docs/guides/migrate/install/weblogic/_index.md
> Install WKO doc review

- content/en/docs/guides/migrate/integrate/prometheus/_index.md
> Review integrate Prometheus doc

- content/en/docs/guides/migrate/integrate/cert-manager/_index.md
> Review integrate cert-manager doc

- content/en/docs/guides/migrate/integrate/oauth2-proxy/_index.md
> review integrate OAuth2 Proxy doc

- content/en/docs/guides/migrate/integrate/fluent/_index.md
> review integrate Fluentd doc

- content/en/docs/guides/migrate/integrate/nginx/_index.md
> Review integrate NGINX doc

- content/en/docs/guides/migrate/integrate/weblogic/_index.md
> Integrate WKO doc review

- content/en/docs/guides/migrate/integrate/opensearch/_index.md
> Integrate OpenSearch review

- content/en/docs/_index.md
Update archive for 1.7.1 and 1.6.11
> Update archive for 1.7.1 and 1.6.11

- content/en/docs/_index.md
In this PR, I update the archive branch for the 1.6.12 and 1.7.2 releases.
> Update archive for 1.6.12 and 1.7.2
